"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Plus, UsersRound, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ApiRequestError, authenticatedApiRequest } from "@/lib/api";

type Chit = { id: number; group_code: string; scheme_name: string; scheme_amount: string; start_date: string; duration_months: number; status: string; members: unknown[] };
export default function ChitsPage() {
  const [groups, setGroups] = useState<Chit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const timer = setTimeout(async () => { try { setGroups(await authenticatedApiRequest<Chit[]>("/api/v1/chits")); } catch (err) { if (err instanceof ApiRequestError && err.status === 401) location.replace("/login"); else setError(err instanceof Error ? err.message : "Unable to load schemes."); } finally { setLoading(false); } }, 0); return () => clearTimeout(timer); }, []);
  return <div className="mx-auto max-w-[1600px] space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Chit operations</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Chit groups</h1><p className="mt-1 text-[13px] text-slate-600">Create schemes, build schedules, enroll members, and collect installments.</p></div><Button nativeButton={false} className="h-9 bg-emerald-600 px-3.5 font-semibold text-white hover:bg-emerald-700" render={<Link href="/dashboard/chits/new" />}><Plus className="size-4" />Create scheme</Button></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading ? <p className="p-8 text-center text-sm text-slate-500">Loading schemes…</p> : groups.length === 0 ? <Card className="border border-dashed border-slate-300 bg-white py-0 ring-0"><CardContent className="p-12 text-center"><WalletCards className="mx-auto size-9 text-slate-400" /><p className="mt-3 text-sm font-bold text-slate-950">No chit schemes yet</p><p className="mt-1 text-xs text-slate-500">Create your first scheme with a generated installment schedule.</p></CardContent></Card> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{groups.map(group => <Card key={group.id} className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="p-4"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold text-emerald-700">{group.group_code}</p><h2 className="mt-1 text-sm font-bold text-slate-950">{group.scheme_name}</h2></div><Badge className={group.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}>{group.status}</Badge></div><p className="mt-4 text-xl font-bold text-slate-950">₹{Number(group.scheme_amount).toLocaleString("en-IN")}</p><div className="mt-3 grid grid-cols-2 gap-2 text-[11px] text-slate-600"><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5" />{group.duration_months} months</span><span className="flex items-center gap-1.5"><UsersRound className="size-3.5" />{group.members.length} members</span></div><Button nativeButton={false} variant="outline" className="mt-4 h-8 w-full text-xs" render={<Link href={`/dashboard/chits/${group.id}`} />}>View scheme <ArrowRight className="size-3.5" /></Button></CardContent></Card>)}</div>}</div>;
}
