"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Download, FileText, Filter, Printer, Scale, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { authenticatedApiRequest } from "@/lib/api";

type Scheme={id:number;group_code:string;scheme_name:string};
type Member={id:number;member_code:string;full_name:string};
type Row={id:string;transaction_type:string;direction:"inflow"|"outflow";transaction_date:string;reference_number:string|null;scheme_id:number|null;scheme_name:string|null;member_id:number|null;member_name:string|null;description:string;payment_mode:string|null;amount:string;status:string};
type Report={rows:Row[];total_inflow:string;total_outflow:string;net_cash_flow:string;transaction_count:number;type_summary:{transaction_type:string;count:number;amount:string}[]};
const empty:Report={rows:[],total_inflow:"0",total_outflow:"0",net_cash_flow:"0",transaction_count:0,type_summary:[]};
const types=[{value:"collection",label:"Collections"},{value:"advance",label:"Advance receipts"},{value:"refund",label:"Refunds"},{value:"auction_payout",label:"Auction payouts"},{value:"payroll",label:"Payroll"}];
const modes=["cash","upi","bank","cheque"].map(value=>({value,label:value.toUpperCase()}));
function money(value:string|number){return `₹${Number(value).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
function dateText(value:string){return new Date(`${value}T00:00:00`).toLocaleDateString("en-IN");}
function readable(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());}
function csvCell(value:unknown){const text=String(value??"");return `"${text.replaceAll('"','""')}"`;}

export default function ReportsPage(){
 const[report,setReport]=useState<Report>(empty);const[schemes,setSchemes]=useState<Scheme[]>([]);const[members,setMembers]=useState<Member[]>([]);const[type,setType]=useState<string|null>(null);const[scheme,setScheme]=useState<string|null>(null);const[member,setMember]=useState<string|null>(null);const[mode,setMode]=useState<string|null>(null);const[from,setFrom]=useState("");const[to,setTo]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 function params(filtered=true){const value=new URLSearchParams();if(filtered&&type)value.set("transaction_type",type);if(filtered&&scheme)value.set("scheme_id",scheme);if(filtered&&member)value.set("member_id",member);if(filtered&&mode)value.set("payment_mode",mode);if(filtered&&from)value.set("date_from",from);if(filtered&&to)value.set("date_to",to);return value;}
 async function load(filtered=true){setLoading(true);setError("");try{setReport(await authenticatedApiRequest<Report>(`/api/v1/dashboard/overall-report?${params(filtered)}`));}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load the overall report.");}finally{setLoading(false);}}
 useEffect(()=>{const timer=setTimeout(async()=>{try{const[data,schemeData,memberData]=await Promise.all([authenticatedApiRequest<Report>("/api/v1/dashboard/overall-report"),authenticatedApiRequest<Scheme[]>("/api/v1/chits"),authenticatedApiRequest<{items:Member[]}>("/api/v1/members?page_size=100")]);setReport(data);setSchemes(schemeData);setMembers(memberData.items);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load report data.");}finally{setLoading(false);}},0);return()=>clearTimeout(timer);},[]);
 function submit(event:FormEvent){event.preventDefault();void load(true);}function clear(){setType(null);setScheme(null);setMember(null);setMode(null);setFrom("");setTo("");setTimeout(()=>void load(false),0);}
 function exportCsv(){const headings=["Date","Type","Direction","Reference","Scheme","Member","Description","Mode","Amount","Status"];const body=report.rows.map(row=>[row.transaction_date,readable(row.transaction_type),readable(row.direction),row.reference_number,row.scheme_name,row.member_name,row.description,row.payment_mode?.toUpperCase(),row.amount,row.status].map(csvCell).join(","));const blob=new Blob([[headings.map(csvCell).join(","),...body].join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`zchit-overall-report-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url);}
 return <div className="mx-auto max-w-[1600px] space-y-4">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Management reports</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Overall report</h1><p className="mt-1 text-[13px] text-slate-600">Consolidated inflows and outflows across collections, advances, refunds, auctions, and payroll.</p></div><div className="flex gap-2 print:hidden"><Button type="button" variant="outline" onClick={exportCsv}><Download className="size-4"/>CSV</Button><Button type="button" variant="outline" onClick={()=>window.print()}><Printer className="size-4"/>PDF</Button></div></div>
  <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0 print:hidden"><CardContent className="overflow-visible p-4"><div className="mb-3 flex items-center gap-2"><span className="flex size-7 items-center justify-center rounded-md bg-emerald-50 text-emerald-700"><Filter className="size-3.5"/></span><div><CardTitle className="text-xs font-bold text-slate-950">Report filters</CardTitle><p className="text-[10px] text-slate-500">Filter the complete financial timeline</p></div></div><form onSubmit={submit} className="grid items-end gap-3 md:grid-cols-2 xl:grid-cols-7"><ReadableSelect label="Transaction" value={type} setValue={setType} placeholder="All transactions" items={types}/><ReadableSelect label="Scheme" value={scheme} setValue={setScheme} placeholder="All schemes" items={schemes.map(item=>({value:String(item.id),label:`${item.scheme_name} · ${item.group_code}`}))}/><ReadableSelect label="Member" value={member} setValue={setMember} placeholder="All members" items={members.map(item=>({value:String(item.id),label:`${item.full_name} · ${item.member_code}`}))}/><ReadableSelect label="Mode" value={mode} setValue={setMode} placeholder="All modes" items={modes}/><DateField label="From" value={from} setValue={setFrom}/><DateField label="To" value={to} setValue={setTo}/><div className="flex h-9 gap-2"><Button type="submit" disabled={loading} className="h-9 flex-1 bg-emerald-600 px-4 text-white hover:bg-emerald-700">Apply</Button><Button type="button" variant="outline" size="icon" className="size-9" onClick={clear} aria-label="Clear"><X className="size-4"/></Button></div></form></CardContent></Card>
  {error&&<p className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={ArrowDownToLine} label="Total inflow" value={money(report.total_inflow)} tone="emerald"/><Stat icon={ArrowUpFromLine} label="Total outflow" value={money(report.total_outflow)} tone="red"/><Stat icon={Scale} label="Net cash flow" value={money(report.net_cash_flow)} tone={Number(report.net_cash_flow)>=0?"blue":"red"}/><Stat icon={FileText} label="Transactions" value={String(report.transaction_count)} tone="amber"/></div>
  <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-200 bg-slate-50 p-4"><div><CardTitle className="text-sm text-slate-950">Financial timeline</CardTitle><p className="mt-0.5 text-[10px] text-slate-500">All records matching the selected filters</p></div><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">{report.rows.length} records</Badge></CardHeader><CardContent className="overflow-x-auto p-0">{loading?<p className="p-10 text-center text-xs text-slate-500">Loading overall report…</p>:report.rows.length===0?<p className="p-10 text-center text-xs text-slate-500">No transactions match these filters.</p>:<table className="w-full min-w-[1250px] text-xs"><thead className="border-b border-slate-200 bg-slate-50"><tr>{["Date","Type","Direction","Reference","Scheme","Member","Description","Mode","Amount","Status"].map(label=><th key={label} className="whitespace-nowrap px-4 py-3 text-left text-[10px] font-bold text-slate-700">{label}</th>)}</tr></thead><tbody>{report.rows.map((row,index)=><tr key={row.id} className={`border-b border-slate-100 ${index%2?"bg-slate-50/60":"bg-white"}`}><td className="whitespace-nowrap px-4 py-3 font-semibold text-slate-900">{dateText(row.transaction_date)}</td><td className="px-4 py-3 font-semibold text-slate-900">{readable(row.transaction_type)}</td><td className="px-4 py-3"><Badge variant="outline" className={row.direction==="inflow"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}>{readable(row.direction)}</Badge></td><td className="px-4 py-3 text-slate-800">{row.reference_number??"—"}</td><td className="px-4 py-3 font-semibold text-slate-900">{row.scheme_name??"Company-wide"}</td><td className="px-4 py-3 font-semibold text-slate-900">{row.member_name??"—"}</td><td className="px-4 py-3 text-slate-800">{row.description}</td><td className="px-4 py-3 font-semibold uppercase text-slate-900">{row.payment_mode??"—"}</td><td className={`px-4 py-3 font-bold ${row.direction==="inflow"?"text-emerald-700":"text-red-700"}`}>{row.direction==="inflow"?"+":"−"}{money(row.amount)}</td><td className="px-4 py-3 text-slate-800">{readable(row.status)}</td></tr>)}</tbody></table>}</CardContent></Card>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{types.map(item=>{const summary=report.type_summary.find(row=>row.transaction_type===item.value);return <Card key={item.value} className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-700">{item.label}</p><p className="mt-2 text-lg font-bold text-slate-950">{money(summary?.amount??0)}</p><p className="mt-1 text-[10px] text-slate-500">{summary?.count??0} records</p></CardContent></Card>})}</div>
 </div>;
}
function ReadableSelect({label,value,setValue,placeholder,items}:{label:string;value:string|null;setValue:(value:string|null)=>void;placeholder:string;items:{value:string;label:string}[]}){const text=items.find(item=>item.value===value)?.label;return <div className="space-y-1.5"><Label className="text-[10px] font-semibold text-slate-700">{label}</Label><Select value={value} onValueChange={setValue}><SelectTrigger className="h-9 w-full border-slate-300 bg-white"><SelectValue>{text??placeholder}</SelectValue></SelectTrigger><SelectContent>{items.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>}
function DateField({label,value,setValue}:{label:string;value:string;setValue:(value:string)=>void}){return <div className="space-y-1.5"><Label className="text-[10px] font-semibold text-slate-700">{label}</Label><Input type="date" value={value} onChange={event=>setValue(event.target.value)} className="h-9"/></div>}
function Stat({icon:Icon,label,value,tone}:{icon:typeof ArrowDownToLine;label:string;value:string;tone:"emerald"|"red"|"blue"|"amber"}){const colors={emerald:"bg-emerald-50 text-emerald-700",red:"bg-red-50 text-red-700",blue:"bg-blue-50 text-blue-700",amber:"bg-amber-50 text-amber-700"};return <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="flex items-center gap-3 p-4"><span className={`flex size-9 items-center justify-center rounded-lg ${colors[tone]}`}><Icon className="size-4"/></span><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-700">{label}</p><p className="mt-1 text-lg font-bold text-slate-950">{value}</p></div></CardContent></Card>}
