from datetime import date, datetime
from decimal import Decimal
from sqlalchemy import Date, DateTime, ForeignKey, Integer, Numeric, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base

class PayrollRun(Base):
    __tablename__="payroll_runs";__table_args__=(UniqueConstraint("company_id","payroll_year","payroll_month",name="uq_payroll_company_period"),)
    id:Mapped[int]=mapped_column(primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="RESTRICT"),index=True);payroll_year:Mapped[int]=mapped_column(Integer);payroll_month:Mapped[int]=mapped_column(Integer);period_start:Mapped[date]=mapped_column(Date);period_end:Mapped[date]=mapped_column(Date);status:Mapped[str]=mapped_column(String(20),default="draft");employee_count:Mapped[int]=mapped_column(Integer,default=0);total_gross_salary:Mapped[Decimal]=mapped_column(Numeric(16,2),default=0);total_deductions:Mapped[Decimal]=mapped_column(Numeric(16,2),default=0);total_net_salary:Mapped[Decimal]=mapped_column(Numeric(16,2),default=0);total_employer_contributions:Mapped[Decimal]=mapped_column(Numeric(16,2),default=0);notes:Mapped[str|None]=mapped_column(String(1000));created_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now());approved_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approval_notes:Mapped[str|None]=mapped_column(String(500));payment_date:Mapped[date|None]=mapped_column(Date);payment_mode:Mapped[str|None]=mapped_column(String(30));payment_reference_number:Mapped[str|None]=mapped_column(String(100));voucher_number:Mapped[str|None]=mapped_column(String(40),unique=True);payment_proof_path:Mapped[str|None]=mapped_column(String(500));payment_proof_file_name:Mapped[str|None]=mapped_column(String(255));paid_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));paid_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));items:Mapped[list["PayrollItem"]]=relationship(cascade="all, delete-orphan",lazy="selectin")

class PayrollItem(Base):
    __tablename__="payroll_items";__table_args__=(UniqueConstraint("payroll_run_id","employee_id",name="uq_payroll_run_employee"),)
    id:Mapped[int]=mapped_column(primary_key=True);payroll_run_id:Mapped[int]=mapped_column(ForeignKey("payroll_runs.id",ondelete="CASCADE"),index=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="RESTRICT"),index=True);employee_id:Mapped[int]=mapped_column(ForeignKey("employees.id",ondelete="RESTRICT"),index=True);salary_structure_id:Mapped[int]=mapped_column(ForeignKey("employee_salary_structures.id",ondelete="RESTRICT"));branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"));employee_code:Mapped[str]=mapped_column(String(24));employee_name:Mapped[str]=mapped_column(String(200));department:Mapped[str]=mapped_column(String(120));designation:Mapped[str]=mapped_column(String(120));total_days:Mapped[Decimal]=mapped_column(Numeric(5,2));payable_days:Mapped[Decimal]=mapped_column(Numeric(5,2));lop_days:Mapped[Decimal]=mapped_column(Numeric(5,2));monthly_basic:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_hra:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_allowances:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_incentives:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_employee_pf:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_employee_esi:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_professional_tax:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_tds:Mapped[Decimal]=mapped_column(Numeric(14,2));monthly_other_deductions:Mapped[Decimal]=mapped_column(Numeric(14,2));gross_salary:Mapped[Decimal]=mapped_column(Numeric(14,2));total_deductions:Mapped[Decimal]=mapped_column(Numeric(14,2));net_salary:Mapped[Decimal]=mapped_column(Numeric(14,2));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
