from datetime import datetime
from sqlalchemy import Boolean,DateTime,ForeignKey,String,Table,Column,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.base import Base
role_permissions=Table("role_permissions",Base.metadata,Column("role_id",ForeignKey("roles.id",ondelete="CASCADE"),primary_key=True),Column("permission_id",ForeignKey("permissions.id",ondelete="CASCADE"),primary_key=True))
class Permission(Base):
    __tablename__="permissions";id:Mapped[int]=mapped_column(primary_key=True);code:Mapped[str]=mapped_column(String(100),unique=True,index=True);module:Mapped[str]=mapped_column(String(60),index=True);name:Mapped[str]=mapped_column(String(120));description:Mapped[str|None]=mapped_column(String(300))
class Role(Base):
    __tablename__="roles";__table_args__=(UniqueConstraint("company_id","name",name="uq_role_company_name"),);id:Mapped[int]=mapped_column(primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(100));description:Mapped[str|None]=mapped_column(String(300));is_system:Mapped[bool]=mapped_column(Boolean,default=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True);created_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now());permissions:Mapped[list[Permission]]=relationship(secondary=role_permissions,lazy="selectin")
class CompanyUser(Base):
    __tablename__="company_users";__table_args__=(UniqueConstraint("company_id","user_id",name="uq_company_user"),);id:Mapped[int]=mapped_column(primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True);user_id:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),unique=True,index=True);employee_id:Mapped[int|None]=mapped_column(ForeignKey("employees.id",ondelete="SET NULL"),unique=True);role_id:Mapped[int]=mapped_column(ForeignKey("roles.id",ondelete="RESTRICT"));branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"));is_active:Mapped[bool]=mapped_column(Boolean,default=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now());role:Mapped[Role]=relationship(lazy="selectin")
