"use client";

import { FormEvent, useEffect, useState } from "react";
import { ChevronDown, ChevronUp, FileClock, Filter, ShieldCheck, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { authenticatedApiRequest } from "@/lib/api";

type Audit = { id:number; user_id:number|null; actor_email:string|null; action:string; entity_type:string; entity_id:number|null; description:string; old_values:Record<string,unknown>|null; new_values:Record<string,unknown>|null; ip_address:string|null; user_agent:string|null; created_at:string };
export default function AuditHistoryPage() {
  const [logs,setLogs]=useState<Audit[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [action,setAction]=useState<string|null>(null); const [entity,setEntity]=useState<string|null>(null); const [dateFrom,setDateFrom]=useState(""); const [dateTo,setDateTo]=useState(""); const [expanded,setExpanded]=useState<number|null>(null);
  async function load(filters=true) { setLoading(true); setError(""); try { const params=new URLSearchParams(); if(filters&&action) params.set("action",action); if(filters&&entity) params.set("entity_type",entity); if(filters&&dateFrom) params.set("date_from",dateFrom); if(filters&&dateTo) params.set("date_to",dateTo); setLogs(await authenticatedApiRequest<Audit[]>(`/api/v1/audit-logs?${params}`)); } catch(err) { setError(err instanceof Error?err.message:"Unable to load audit history."); } finally { setLoading(false); } }
  useEffect(()=>{const timer=setTimeout(async()=>{try{setLogs(await authenticatedApiRequest<Audit[]>("/api/v1/audit-logs"));}catch(err){setError(err instanceof Error?err.message:"Unable to load audit history.");}finally{setLoading(false);}},0);return()=>clearTimeout(timer);},[]); function submit(event:FormEvent){event.preventDefault();void load(true);} function clear(){setAction(null);setEntity(null);setDateFrom("");setDateTo("");setTimeout(()=>void load(false),0);}
  return <div className="mx-auto max-w-[1600px] space-y-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Governance</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Audit history</h1><p className="mt-1 text-[13px] text-slate-600">Review actor, action, entity, change values, timestamp, and request context.</p></div>
  <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="overflow-visible p-4"><div className="mb-3 flex items-center gap-2"><Filter className="size-4 text-emerald-700"/><CardTitle className="text-xs">History filters</CardTitle></div><form onSubmit={submit} className="grid items-end gap-3 md:grid-cols-2 xl:grid-cols-[1fr_1fr_160px_160px_auto]"><ReadableSelect label="Action" value={action} setValue={setAction} placeholder="All actions" items={["create","update","allocate","reverse","replace","archive"].map(value=>({value,label:title(value)}))}/><ReadableSelect label="Entity" value={entity} setValue={setEntity} placeholder="All entities" items={["advance_payment","payment","auction","member","chit_group","schedule","enrollment","company","branch"].map(value=>({value,label:title(value)}))}/><Field label="From date" value={dateFrom} setValue={setDateFrom}/><Field label="To date" value={dateTo} setValue={setDateTo}/><div className="flex h-9 gap-2"><Button type="submit" className="h-9 bg-emerald-600 text-white">Apply</Button><Button type="button" variant="outline" size="icon" className="size-9" onClick={clear}><X className="size-4"/></Button></div></form></CardContent></Card>
  {error&&<p className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><Card className="border border-slate-200 bg-white py-0 ring-0"><CardContent className="flex items-center gap-3 p-4"><FileClock className="size-6 text-emerald-700"/><div><p className="text-xs font-semibold text-slate-600">Matching events</p><p className="text-xl font-bold text-slate-950">{logs.length}</p></div></CardContent></Card><Card className="border border-slate-200 bg-white py-0 ring-0"><CardContent className="flex items-center gap-3 p-4"><ShieldCheck className="size-6 text-emerald-700"/><div><p className="text-xs font-semibold text-slate-600">Audit retention</p><p className="text-sm font-bold text-slate-950">Append-only company history</p></div></CardContent></Card></div>
  <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-200 bg-slate-50 p-4"><div><CardTitle className="text-sm">Activity log</CardTitle><p className="mt-1 text-[10px] text-slate-500">Latest company events appear first.</p></div><Badge variant="outline">{logs.length} events</Badge></CardHeader><CardContent className="p-0">{loading?<p className="p-10 text-center text-xs text-slate-500">Loading audit history…</p>:logs.length===0?<p className="p-10 text-center text-xs text-slate-500">No audit events match these filters.</p>:<div>{logs.map(log=><div key={log.id} className="border-b border-slate-100 last:border-0"><button type="button" onClick={()=>setExpanded(expanded===log.id?null:log.id)} className="grid w-full gap-3 px-4 py-3 text-left hover:bg-emerald-50/50 md:grid-cols-[155px_120px_160px_1fr_210px_25px] md:items-center"><span className="text-[11px] font-semibold text-slate-700">{new Date(log.created_at).toLocaleString("en-IN")}</span><Badge className="w-fit bg-emerald-50 text-emerald-700">{title(log.action)}</Badge><span><p className="text-xs font-bold text-slate-950">{title(log.entity_type)}</p><p className="text-[9px] text-slate-500">Record {log.entity_id??"—"}</p></span><span className="text-xs font-semibold text-slate-800">{log.description}</span><span><p className="truncate text-xs font-semibold text-slate-800">{log.actor_email??"System"}</p><p className="text-[9px] text-slate-500">{log.ip_address??"IP unavailable"}</p></span>{expanded===log.id?<ChevronUp className="size-4"/>:<ChevronDown className="size-4"/>}</button>{expanded===log.id&&<div className="grid gap-3 border-t border-slate-100 bg-slate-50 px-4 py-4 md:grid-cols-2"><JsonPanel title="Previous values" value={log.old_values}/><JsonPanel title="New values" value={log.new_values}/><div className="md:col-span-2"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-600">User agent</p><p className="mt-1 break-all text-[11px] text-slate-700">{log.user_agent??"Not recorded"}</p></div></div>}</div>)}</div>}</CardContent></Card></div>;
}
function ReadableSelect({label,value,setValue,placeholder,items}:{label:string;value:string|null;setValue:(value:string|null)=>void;placeholder:string;items:{value:string;label:string}[]}) { const selected=items.find(item=>item.value===value)?.label; return <div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">{label}</Label><Select value={value} onValueChange={setValue}><SelectTrigger className="h-9 w-full"><SelectValue>{selected??placeholder}</SelectValue></SelectTrigger><SelectContent>{items.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>; }
function Field({label,value,setValue}:{label:string;value:string;setValue:(value:string)=>void}) { return <div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">{label}</Label><Input type="date" value={value} onChange={event=>setValue(event.target.value)} className="h-9"/></div>; }
function JsonPanel({title,value}:{title:string;value:Record<string,unknown>|null}) { return <div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-600">{title}</p><pre className="mt-1 overflow-x-auto rounded-md border border-slate-200 bg-white p-3 text-[11px] text-slate-800">{value?JSON.stringify(value,null,2):"No values recorded"}</pre></div>; }
function title(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());}
