"use client";

import Link from "next/link";
import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Banknote, Camera, FileUp, MapPin, Plus, Trash2, UserRound, UsersRound } from "lucide-react";
import { FormMessage } from "@/components/auth/form-message";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { API_URL, authenticatedApiRequest, getResponseError } from "@/lib/api";

const fieldClass = "h-9 border-slate-300 bg-white text-sm text-slate-950";
type Reference = { id: number };

export default function NewMemberPage() {
  const router = useRouter(); const [references, setReferences] = useState<Reference[]>([{ id: 1 }]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [photo, setPhoto] = useState<File | null>(null); const [aadhaarDocument, setAadhaarDocument] = useState<File | null>(null); const [panDocument, setPanDocument] = useState<File | null>(null); const [cheque, setCheque] = useState<File | null>(null); const [statement, setStatement] = useState<File | null>(null);
  const photoPreview = useMemo(() => photo ? URL.createObjectURL(photo) : null, [photo]);
  useEffect(() => () => { if (photoPreview) URL.revokeObjectURL(photoPreview); }, [photoPreview]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); const optional = (name: string) => String(data.get(name) ?? "").trim() || null; try { const member = await authenticatedApiRequest<{ id: number }>("/api/v1/members", { method: "POST", body: JSON.stringify({ full_name: data.get("full_name"), date_of_birth: optional("date_of_birth"), mobile_number: data.get("mobile_number"), email: optional("email"), aadhaar_number: data.get("aadhaar_number"), pan: optional("pan"), nominee_name: optional("nominee_name"), nominee_relationship: optional("nominee_relationship"), nominee_mobile_number: optional("nominee_mobile_number"), nominee_date_of_birth: optional("nominee_date_of_birth"), bank_account_holder_name: optional("bank_account_holder_name"), bank_account_number: optional("bank_account_number"), bank_name: optional("bank_name"), bank_branch_name: optional("bank_branch_name"), bank_ifsc_code: optional("bank_ifsc_code"), bank_account_type: optional("bank_account_type")?.toLowerCase(), address_line_1: data.get("address_line_1"), address_line_2: optional("address_line_2"), locality: optional("locality"), city: data.get("city"), state: data.get("state"), postal_code: data.get("postal_code"), country: "India", landmark: optional("landmark"), references: references.map((_, i) => ({ name: data.get(`reference_name_${i}`), mobile_number: data.get(`reference_number_${i}`), relationship: optional(`reference_relationship_${i}`) })) }) }); if (photo || aadhaarDocument || panDocument || cheque || statement) { const documents = new FormData(); if (photo) documents.append("photo", photo); if (aadhaarDocument) documents.append("aadhaar_document", aadhaarDocument); if (panDocument) documents.append("pan_document", panDocument); if (cheque) documents.append("cheque", cheque); if (statement) documents.append("bank_statement", statement); const token = localStorage.getItem("zchit_access_token"); const response = await fetch(`${API_URL}/api/v1/members/${member.id}/documents`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: documents }); if (!response.ok) throw new Error(await getResponseError(response, "Member saved, but file upload failed.")); } router.push("/dashboard/members"); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create member."); } finally { setLoading(false); } }
  return <div className="mx-auto max-w-3xl space-y-3"><div className="flex items-center gap-3"><Button nativeButton={false} variant="outline" size="icon" render={<Link href="/dashboard/members" />}><ArrowLeft className="size-4" /></Button><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-700">Member management</p><h1 className="mt-0.5 text-lg font-bold text-slate-950">Add new member</h1></div></div><form onSubmit={submit} className="space-y-3">{error && <FormMessage type="error">{error}</FormMessage>}
  <Section icon={UserRound} title="Personal & KYC information"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_120px]"><Field label="Full name" name="full_name" required /><Field label="Date of birth" name="date_of_birth" type="date" /><PhotoUpload file={photo} preview={photoPreview} onChange={setPhoto} /><Field label="Mobile number" name="mobile_number" required placeholder="+919876543210" /><Field label="Email" name="email" type="email" /><Field label="Aadhaar number" name="aadhaar_number" required placeholder="12 digits" maxLength={14} /><Field label="PAN" name="pan" maxLength={10} /></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Upload label="Aadhaar document" file={aadhaarDocument} onChange={setAadhaarDocument} /><Upload label="PAN document" file={panDocument} onChange={setPanDocument} /></div><p className="mt-2 rounded-md bg-emerald-50 px-2.5 py-2 text-[10px] text-emerald-900">Aadhaar number is stored only as a one-way hash. Identity files are stored privately.</p></Section>
  <Section icon={UsersRound} title="Nominee details"><div className="grid gap-3 sm:grid-cols-2"><Field label="Nominee name" name="nominee_name" /><Field label="Relationship" name="nominee_relationship" /><Field label="Mobile number" name="nominee_mobile_number" placeholder="+919876543210" /><Field label="Date of birth" name="nominee_date_of_birth" type="date" /></div></Section>
  <Section icon={MapPin} title="Residential address"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Address line 1" name="address_line_1" required /></div><div className="sm:col-span-2"><Field label="Address line 2" name="address_line_2" /></div><Field label="Locality" name="locality" /><Field label="Landmark" name="landmark" /><Field label="City" name="city" required /><Field label="State" name="state" required /><Field label="Postal code" name="postal_code" required /><div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">Country</Label><Input value="India" readOnly className={`${fieldClass} bg-slate-50`} /></div></div></Section>
  <Section icon={UserRound} title="References"><div className="space-y-3">{references.map((reference, index) => <div key={reference.id} className="grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3 sm:grid-cols-[1fr_1fr_.8fr_auto]"><Field label="Reference name" name={`reference_name_${index}`} required /><Field label="Mobile number" name={`reference_number_${index}`} required /><Field label="Relationship" name={`reference_relationship_${index}`} />{references.length > 1 && <Button type="button" variant="ghost" size="icon" className="self-end text-red-700" onClick={() => setReferences(current => current.filter(item => item.id !== reference.id))}><Trash2 className="size-4" /></Button>}</div>)}<Button type="button" variant="outline" className="h-8 text-xs" onClick={() => setReferences(current => [...current, { id: Date.now() }])}><Plus className="size-3.5" />Add reference</Button></div></Section>
  <Section icon={Banknote} title="Bank account details"><div className="grid gap-3 sm:grid-cols-2"><Field label="Account holder name" name="bank_account_holder_name" /><Field label="Account number" name="bank_account_number" /><Field label="Bank name" name="bank_name" /><Field label="Branch name" name="bank_branch_name" /><Field label="IFSC code" name="bank_ifsc_code" maxLength={11} /><Field label="Account type" name="bank_account_type" placeholder="savings / current / other" /></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Upload label="Cancelled cheque" file={cheque} onChange={setCheque} /><Upload label="Bank statement" file={statement} onChange={setStatement} /></div><p className="mt-2 text-[10px] text-slate-500">PDF, JPEG, or PNG · maximum 10 MB each. Stored privately.</p></Section>
  <div className="flex justify-end"><Button type="submit" disabled={loading} className="h-9 bg-emerald-600 px-5 font-semibold text-white hover:bg-emerald-700">{loading ? "Creating member…" : <>Create member <ArrowRight className="size-4" /></>}</Button></div></form></div>;
}

function Section({ icon: Icon, title, children }: { icon: typeof UserRound; title: string; children: React.ReactNode }) { return <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="border-b border-slate-200 px-3.5 py-3"><div className="flex items-center gap-2"><span className="flex size-7 items-center justify-center rounded-md bg-emerald-50 text-emerald-700"><Icon className="size-3.5" /></span><CardTitle className="text-xs font-bold text-slate-950">{title}</CardTitle></div></CardHeader><CardContent className="overflow-visible p-3.5">{children}</CardContent></Card>; }
function Field({ label, name, required, type = "text", placeholder, maxLength }: { label: string; name: string; required?: boolean; type?: string; placeholder?: string; maxLength?: number }) { return <div className="space-y-1.5"><Label htmlFor={name} className="text-xs font-semibold text-slate-700">{label}{required && <span className="text-red-600"> *</span>}</Label><Input id={name} name={name} type={type} required={required} placeholder={placeholder} maxLength={maxLength} className={fieldClass} /></div>; }
function Upload({ label, file, onChange }: { label: string; file: File | null; onChange: (file: File | null) => void }) { return <label className="flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-slate-300 p-3 hover:bg-slate-50"><span className="flex size-9 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FileUp className="size-4" /></span><div className="min-w-0"><p className="text-xs font-bold text-slate-800">{label}</p><p className="truncate text-[10px] text-slate-500">{file?.name ?? "Choose file"}</p></div><input type="file" accept="application/pdf,image/jpeg,image/png" className="hidden" onChange={(event) => onChange(event.target.files?.[0] ?? null)} /></label>; }
function PhotoUpload({ file, preview, onChange }: { file: File | null; preview: string | null; onChange: (file: File | null) => void }) { return <label className="row-span-2 flex cursor-pointer flex-col items-center justify-center overflow-hidden rounded-lg border border-dashed border-slate-300 bg-slate-50 p-2 text-center hover:bg-slate-100">{preview ? <Image src={preview} alt="Member photo preview" width={72} height={72} unoptimized className="size-[72px] rounded-lg object-cover" /> : <span className="flex size-10 items-center justify-center rounded-full bg-white text-slate-600 shadow-sm"><Camera className="size-4" /></span>}<p className="mt-1.5 max-w-[100px] truncate text-[10px] font-semibold text-slate-700">{file?.name ?? "Member photo"}</p><input type="file" accept="image/jpeg,image/png" className="hidden" onChange={(event) => onChange(event.target.files?.[0] ?? null)} /></label>; }
