"use client";

import { FormEvent, useEffect, useState } from "react";
import { Download, Filter, Pencil, Plus, Printer, ReceiptIndianRupee, Search, Trash2, WalletCards, X } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { authenticatedApiRequest } from "@/lib/api";

type Expense = { id: number; expense_date: string; category: string; amount: string; branch_id: number | null; branch_name: string | null; payee: string | null; payment_mode: string; reference_number: string | null; description: string; notes: string | null; created_by: string | null; created_at: string; updated_at: string };
type ExpenseList = { items: Expense[]; total_amount: string; count: number; category_totals: Record<string, string> };
type Branch = { id: number; branch_code: string; name: string; is_active: boolean };
type FormState = { expense_date: string; category: string | null; amount: string; branch_id: string | null; payee: string; payment_mode: string | null; reference_number: string; description: string; notes: string };

const today = new Date().toISOString().slice(0, 10);
const emptyForm: FormState = { expense_date: today, category: "food", amount: "", branch_id: null, payee: "", payment_mode: "cash", reference_number: "", description: "", notes: "" };
const categories = [
  { value: "food", label: "Food" }, { value: "petrol_allowance", label: "Petrol allowance" },
  { value: "snacks", label: "Snacks" }, { value: "broadband_bill", label: "Broadband bill" },
  { value: "courier_bill", label: "Courier bill" }, { value: "recharge", label: "Recharge" },
  { value: "others", label: "Others" },
];
const modes = ["cash", "upi", "bank", "cheque", "card"].map(value => ({ value, label: value.toUpperCase() }));
const emptyList: ExpenseList = { items: [], total_amount: "0", count: 0, category_totals: {} };

function money(value: string | number) { return `₹${Number(value).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function dateText(value: string) { return new Date(`${value}T00:00:00`).toLocaleDateString("en-IN"); }
function labelFor(value: string) { return categories.find(item => item.value === value)?.label ?? value.replaceAll("_", " "); }
function csvCell(value: unknown) { return `"${String(value ?? "").replaceAll('"', '""')}"`; }

export default function ExpensesPage() {
  const [data, setData] = useState<ExpenseList>(emptyList); const [branches, setBranches] = useState<Branch[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [search, setSearch] = useState(""); const [category, setCategory] = useState<string | null>(null); const [mode, setMode] = useState<string | null>(null); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Expense | null>(null); const [form, setForm] = useState<FormState>(emptyForm); const [saving, setSaving] = useState(false); const [deletingId, setDeletingId] = useState<number | null>(null);

  function query(filtered = true) { const params = new URLSearchParams(); if (filtered && search.trim()) params.set("search", search.trim()); if (filtered && category) params.set("category", category); if (filtered && mode) params.set("payment_mode", mode); if (filtered && from) params.set("date_from", from); if (filtered && to) params.set("date_to", to); return params; }
  async function load(filtered = true) { setLoading(true); setError(""); try { setData(await authenticatedApiRequest<ExpenseList>(`/api/v1/expenses?${query(filtered)}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load expenses."); } finally { setLoading(false); } }
  useEffect(() => { const timer = setTimeout(async () => { try { const [expenses, branchData] = await Promise.all([authenticatedApiRequest<ExpenseList>("/api/v1/expenses"), authenticatedApiRequest<Branch[]>("/api/v1/branches").catch(() => [])]); setData(expenses); setBranches(branchData.filter(item => item.is_active)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load expenses."); } finally { setLoading(false); } }, 0); return () => clearTimeout(timer); }, []);

  function resetForm() { setEditing(null); setForm(emptyForm); }
  function edit(row: Expense) { setEditing(row); setForm({ expense_date: row.expense_date, category: row.category, amount: row.amount, branch_id: row.branch_id ? String(row.branch_id) : null, payee: row.payee ?? "", payment_mode: row.payment_mode, reference_number: row.reference_number ?? "", description: row.description, notes: row.notes ?? "" }); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); if (!form.category || !form.payment_mode) return; setSaving(true); setError(""); try { const payload = { ...form, branch_id: form.branch_id ? Number(form.branch_id) : null, payee: form.payee || null, reference_number: form.reference_number || null, notes: form.notes || null }; await authenticatedApiRequest(editing ? `/api/v1/expenses/${editing.id}` : "/api/v1/expenses", { method: editing ? "PUT" : "POST", body: JSON.stringify(payload) }); setOpen(false); resetForm(); await load(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save expense."); } finally { setSaving(false); } }
  async function remove(id: number) { setDeletingId(id); setError(""); try { await authenticatedApiRequest(`/api/v1/expenses/${id}`, { method: "DELETE" }); await load(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to delete expense."); } finally { setDeletingId(null); } }
  function submitFilters(event: FormEvent) { event.preventDefault(); void load(true); }
  function clearFilters() { setSearch(""); setCategory(null); setMode(null); setFrom(""); setTo(""); setTimeout(() => void load(false), 0); }
  function exportCsv() { const headings = ["Date", "Category", "Description", "Payee", "Branch", "Mode", "Reference", "Amount", "Notes"]; const rows = data.items.map(row => [row.expense_date, labelFor(row.category), row.description, row.payee, row.branch_name, row.payment_mode.toUpperCase(), row.reference_number, row.amount, row.notes].map(csvCell).join(",")); const blob = new Blob([[headings.map(csvCell).join(","), ...rows].join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `zchit-expenses-${today}.csv`; anchor.click(); URL.revokeObjectURL(url); }

  const highestCategory = Object.entries(data.category_totals).sort(([, left], [, right]) => Number(right) - Number(left))[0];
  return <div className="mx-auto max-w-[1600px] space-y-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Company spending</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Expenses</h1><p className="mt-1 text-[13px] text-slate-600">Record, review, and export day-to-day operating expenses.</p></div><div className="flex flex-wrap gap-2 print:hidden"><Button type="button" variant="outline" onClick={exportCsv} disabled={!data.items.length}><Download className="size-4" />CSV</Button><Button type="button" variant="outline" onClick={() => window.print()} disabled={!data.items.length}><Printer className="size-4" />PDF</Button><Sheet open={open} onOpenChange={value => { setOpen(value); if (!value) resetForm(); }}><SheetTrigger render={<Button className="bg-emerald-600 text-white hover:bg-emerald-700" />}><Plus className="size-4" />Add expense</SheetTrigger><SheetContent className="overflow-y-auto sm:max-w-md"><SheetHeader><SheetTitle>{editing ? "Edit expense" : "Add expense"}</SheetTitle></SheetHeader><ExpenseForm form={form} setForm={setForm} branches={branches} saving={saving} editing={Boolean(editing)} onSubmit={save} /></SheetContent></Sheet></div></div>

    <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0 print:hidden"><CardContent className="overflow-visible p-4"><div className="mb-3 flex items-center gap-2"><span className="flex size-7 items-center justify-center rounded-md bg-emerald-50 text-emerald-700"><Filter className="size-3.5" /></span><div><CardTitle className="text-xs font-bold text-slate-950">Expense filters</CardTitle><p className="text-[10px] text-slate-500">Search and narrow the expense register</p></div></div><form onSubmit={submitFilters} className="grid items-end gap-3 md:grid-cols-2 xl:grid-cols-[1.3fr_1fr_1fr_150px_150px_auto]"><TextField label="Search" value={search} setValue={setSearch} placeholder="Description, payee, reference…" icon /><ReadableSelect label="Category" value={category} setValue={setCategory} placeholder="All categories" items={categories} /><ReadableSelect label="Payment mode" value={mode} setValue={setMode} placeholder="All modes" items={modes} /><TextField label="From" value={from} setValue={setFrom} type="date" /><TextField label="To" value={to} setValue={setTo} type="date" /><div className="flex h-9 gap-2"><Button type="submit" disabled={loading} className="h-9 bg-emerald-600 px-4 text-white hover:bg-emerald-700">Apply</Button><Button type="button" variant="outline" size="icon" className="size-9" onClick={clearFilters} aria-label="Clear filters"><X className="size-4" /></Button></div></form></CardContent></Card>

    {error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 print:hidden">{error}</p>}
    <div className="grid gap-3 sm:grid-cols-3"><Summary icon={WalletCards} label="Total expenses" value={money(data.total_amount)} /><Summary icon={ReceiptIndianRupee} label="Records" value={String(data.count)} /><Summary icon={Filter} label="Highest category" value={highestCategory ? `${labelFor(highestCategory[0])} · ${money(highestCategory[1])}` : "No expenses"} /></div>

    <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-200 bg-slate-50 p-4"><div><CardTitle className="text-sm text-slate-950">Expense register</CardTitle><p className="mt-0.5 text-[10px] text-slate-500">Records matching the selected filters</p></div><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">{data.count} records</Badge></CardHeader><CardContent className="p-0">{loading ? <p className="p-10 text-center text-xs text-slate-500">Loading expenses…</p> : data.items.length === 0 ? <div className="p-10 text-center"><ReceiptIndianRupee className="mx-auto size-8 text-slate-400" /><p className="mt-3 text-sm font-semibold text-slate-900">No expenses found</p><p className="mt-1 text-xs text-slate-500">Add an expense or adjust the current filters.</p></div> : <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1050px] text-xs"><thead className="border-b border-slate-200 bg-slate-50"><tr>{["Date", "Category", "Expense", "Branch", "Mode", "Reference", "Amount", "Actions"].map(label => <th key={label} className="whitespace-nowrap px-4 py-3 text-left text-[10px] font-bold text-slate-700">{label}</th>)}</tr></thead><tbody>{data.items.map((row, index) => <ExpenseRow key={row.id} row={row} index={index} editing={() => edit(row)} deletingId={deletingId} remove={remove} />)}</tbody></table></div><div className="divide-y divide-slate-200 md:hidden">{data.items.map(row => <ExpenseCard key={row.id} row={row} editing={() => edit(row)} deletingId={deletingId} remove={remove} />)}</div></>}</CardContent></Card>
  </div>;
}

function ExpenseForm({ form, setForm, branches, saving, editing, onSubmit }: { form: FormState; setForm: (form: FormState) => void; branches: Branch[]; saving: boolean; editing: boolean; onSubmit: (event: FormEvent) => void }) { function set<K extends keyof FormState>(key: K, value: FormState[K]) { setForm({ ...form, [key]: value }); } return <form onSubmit={onSubmit} className="space-y-4 px-4 pb-6"><div className="grid grid-cols-2 gap-3"><TextField label="Expense date" type="date" value={form.expense_date} setValue={value => set("expense_date", value)} required /><TextField label="Amount" type="number" value={form.amount} setValue={value => set("amount", value)} required /></div><ReadableSelect label="Category" value={form.category} setValue={value => set("category", value)} placeholder="Select category" items={categories} />{branches.length > 0 && <ReadableSelect label="Branch" value={form.branch_id} setValue={value => set("branch_id", value)} placeholder="Company-wide" items={branches.map(branch => ({ value: String(branch.id), label: `${branch.name} · ${branch.branch_code}` }))} />}<ReadableSelect label="Payment mode" value={form.payment_mode} setValue={value => set("payment_mode", value)} placeholder="Select mode" items={modes} /><TextField label="Description" value={form.description} setValue={value => set("description", value)} placeholder="What was this expense for?" required /><TextField label="Payee" value={form.payee} setValue={value => set("payee", value)} placeholder="Vendor or recipient" /><TextField label="Reference number" value={form.reference_number} setValue={value => set("reference_number", value)} placeholder="Optional transaction reference" /><TextField label="Notes" value={form.notes} setValue={value => set("notes", value)} placeholder="Optional internal note" /><Button type="submit" disabled={saving || !form.amount || !form.category || !form.payment_mode || !form.description.trim()} className="h-9 w-full bg-emerald-600 text-white hover:bg-emerald-700">{saving ? "Saving…" : editing ? "Save changes" : "Add expense"}</Button></form>; }
function ExpenseRow({ row, index, editing, deletingId, remove }: { row: Expense; index: number; editing: () => void; deletingId: number | null; remove: (id: number) => Promise<void> }) { return <tr className={`border-b border-slate-100 ${index % 2 ? "bg-slate-50/60" : "bg-white"}`}><td className="whitespace-nowrap px-4 py-3 font-semibold text-slate-900">{dateText(row.expense_date)}</td><td className="px-4 py-3"><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">{labelFor(row.category)}</Badge></td><td className="px-4 py-3"><p className="font-semibold text-slate-950">{row.description}</p><p className="mt-0.5 text-[10px] text-slate-500">{row.payee ?? "No payee"}</p></td><td className="px-4 py-3 text-slate-800">{row.branch_name ?? "Company-wide"}</td><td className="px-4 py-3 font-semibold uppercase text-slate-800">{row.payment_mode}</td><td className="px-4 py-3 text-slate-800">{row.reference_number ?? "—"}</td><td className="px-4 py-3 text-sm font-bold text-slate-950">{money(row.amount)}</td><td className="px-4 py-3 print:hidden"><RowActions row={row} editing={editing} deletingId={deletingId} remove={remove} /></td></tr>; }
function ExpenseCard({ row, editing, deletingId, remove }: { row: Expense; editing: () => void; deletingId: number | null; remove: (id: number) => Promise<void> }) { return <div className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">{labelFor(row.category)}</Badge><p className="mt-2 text-sm font-bold text-slate-950">{row.description}</p><p className="mt-1 text-xs text-slate-600">{row.payee ?? "No payee"} · {dateText(row.expense_date)}</p></div><p className="whitespace-nowrap text-base font-bold text-slate-950">{money(row.amount)}</p></div><div className="flex items-center justify-between border-t border-slate-100 pt-3"><p className="text-xs font-semibold text-slate-700">{row.payment_mode.toUpperCase()} · {row.branch_name ?? "Company-wide"}</p><RowActions row={row} editing={editing} deletingId={deletingId} remove={remove} /></div></div>; }
function RowActions({ row, editing, deletingId, remove }: { row: Expense; editing: () => void; deletingId: number | null; remove: (id: number) => Promise<void> }) { return <div className="flex gap-1"><Button type="button" variant="ghost" size="icon-sm" onClick={editing} aria-label="Edit expense"><Pencil className="size-3.5" /></Button><AlertDialog><AlertDialogTrigger render={<Button type="button" variant="ghost" size="icon-sm" className="text-red-700 hover:bg-red-50 hover:text-red-800" disabled={deletingId === row.id} aria-label="Delete expense" />}><Trash2 className="size-3.5" /></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this expense?</AlertDialogTitle><AlertDialogDescription>This permanently removes {labelFor(row.category).toLowerCase()} expense of {money(row.amount)} from the register.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => void remove(row.id)}>Delete expense</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>; }
function ReadableSelect({ label, value, setValue, placeholder, items }: { label: string; value: string | null; setValue: (value: string | null) => void; placeholder: string; items: { value: string; label: string }[] }) { const text = items.find(item => item.value === value)?.label; return <div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">{label}</Label><Select value={value} onValueChange={setValue}><SelectTrigger className="h-9 w-full border-slate-300 bg-white"><SelectValue>{text ?? placeholder}</SelectValue></SelectTrigger><SelectContent>{items.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>; }
function TextField({ label, value, setValue, type = "text", placeholder, required = false, icon = false }: { label: string; value: string; setValue: (value: string) => void; type?: string; placeholder?: string; required?: boolean; icon?: boolean }) { return <div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">{label}</Label><div className="relative">{icon && <Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-slate-500" />}<Input type={type} value={value} onChange={event => setValue(event.target.value)} placeholder={placeholder} required={required} min={type === "number" ? "0.01" : undefined} step={type === "number" ? "0.01" : undefined} className={`h-9 ${icon ? "pl-9" : ""}`} /></div></div>; }
function Summary({ icon: Icon, label, value }: { icon: typeof WalletCards; label: string; value: string }) { return <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="flex items-center gap-3 p-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700"><Icon className="size-5" /></span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-700">{label}</p><p className="mt-1 truncate text-lg font-bold text-slate-950">{value}</p></div></CardContent></Card>; }