"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, CalendarRange, Search, UsersRound, WalletCards } from "lucide-react";
import { FormMessage } from "@/components/auth/form-message";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { authenticatedApiRequest } from "@/lib/api";

type Schedule = { id: number; installment_number: number; due_date: string; payable_amount: string; receivable_amount: string };
type Member = { id: number; member_code: string; full_name: string; mobile_number: string };
type Chit = { id: number; group_code: string; scheme_name: string; scheme_amount: string; duration_months: number; schedules: Schedule[] };
export default function NewChitPage() {
  const router = useRouter(); const [step, setStep] = useState(1); const [group, setGroup] = useState<Chit | null>(null); const [schedule, setSchedule] = useState<Schedule[]>([]); const [members, setMembers] = useState<Member[]>([]); const [memberSearch, setMemberSearch] = useState(""); const [selected, setSelected] = useState<number[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const filteredMembers = members.filter((member) => {
    const query = memberSearch.trim().toLowerCase();
    return !query || member.full_name.toLowerCase().includes(query) || member.mobile_number.toLowerCase().includes(query) || member.member_code.toLowerCase().includes(query);
  });
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); try { const created = await authenticatedApiRequest<Chit>("/api/v1/chits", { method: "POST", body: JSON.stringify({ scheme_name: data.get("scheme_name"), scheme_amount: Number(data.get("scheme_amount")), start_date: data.get("start_date"), duration_months: Number(data.get("duration_months")), max_member_count: Number(data.get("max_member_count")), foreman_commission_percent: Number(data.get("foreman_commission_percent") || 0), grace_period_days: Number(data.get("grace_period_days") || 0), late_fee_type: data.get("late_fee_type") || "none", late_fee_value: Number(data.get("late_fee_value") || 0) }) }); setGroup(created); setSchedule(created.schedules); setStep(2); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create scheme."); } finally { setLoading(false); } }
  async function saveSchedule() { if (!group) return; setLoading(true); try { await authenticatedApiRequest(`/api/v1/chits/${group.id}/schedule`, { method: "PUT", body: JSON.stringify({ schedules: schedule }) }); const memberData = await authenticatedApiRequest<{ items: Member[] }>("/api/v1/members?page_size=100"); setMembers(memberData.items); setStep(3); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save schedule."); } finally { setLoading(false); } }
  async function saveMembers() { if (!group) return; if (!selected.length) { setError("Select at least one member."); return; } setLoading(true); try { await authenticatedApiRequest(`/api/v1/chits/${group.id}/members`, { method: "PUT", body: JSON.stringify({ member_ids: selected }) }); setStep(4); } catch (err) { setError(err instanceof Error ? err.message : "Unable to enroll members."); } finally { setLoading(false); } }
  return <div className="mx-auto max-w-5xl space-y-4"><div className="flex items-center gap-3"><Button nativeButton={false} variant="outline" size="icon" render={<Link href="/dashboard/chits" />}><ArrowLeft className="size-4" /></Button><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-700">New chit group</p><h1 className="mt-0.5 text-lg font-bold text-slate-950">Create scheme</h1></div></div><Steps current={step} />{error && <FormMessage type="error">{error}</FormMessage>}
  {step === 1 && <form onSubmit={create}><Card className="mx-auto max-w-3xl border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="border-b border-slate-200 p-4"><CardTitle className="text-sm font-bold">Scheme details</CardTitle></CardHeader><CardContent className="grid gap-4 p-4 sm:grid-cols-2"><Field label="Scheme name" name="scheme_name" required /><Field label="Scheme amount" name="scheme_amount" type="number" required /><Field label="Start date" name="start_date" type="date" required /><Field label="Duration (months)" name="duration_months" type="number" required min={2} max={120} /><Field label="Maximum members / slots" name="max_member_count" type="number" required min={1} max={1000} /><Field label="Foreman commission (%)" name="foreman_commission_percent" type="number" min={0} max={100} /><Field label="Grace period (days)" name="grace_period_days" type="number" min={0} max={365} /><div className="space-y-1.5"><Label className="text-xs font-semibold">Late fee rule</Label><select name="late_fee_type" className="h-9 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-900"><option value="none">No late fee</option><option value="fixed">Fixed amount</option><option value="percentage">Percentage</option></select></div><Field label="Late fee value" name="late_fee_value" type="number" min={0} /><div className="sm:col-span-2 flex justify-end"><Button type="submit" disabled={loading} className="h-9 bg-emerald-600 text-white">{loading ? "Generating…" : <>Generate schedule <ArrowRight className="size-4" /></>}</Button></div></CardContent></Card></form>}
  {step === 2 && <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-200 p-4"><div><CardTitle className="text-sm font-bold">Installment schedule</CardTitle><p className="mt-1 text-[11px] text-slate-500">Payable is the member installment. Enter the auction winner&apos;s receivable amount manually.</p></div><Badge>{schedule.length} rows</Badge></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead className="bg-slate-50"><tr><th className="p-3 text-left">#</th><th className="p-3 text-left">Date</th><th className="p-3 text-left">Payable amount</th><th className="p-3 text-left">Receivable amount</th></tr></thead><tbody>{schedule.map((row, index) => <tr key={row.id} className="border-t border-slate-100"><td className="p-2.5 font-bold">{row.installment_number}</td>{(["due_date","payable_amount","receivable_amount"] as const).map(key => <td key={key} className="p-2.5"><Input type={key === "due_date" ? "date" : "number"} min={key === "due_date" ? undefined : 0} step={key === "due_date" ? undefined : "0.01"} value={row[key]} onChange={e => setSchedule(current => current.map((item, i) => i === index ? { ...item, [key]: e.target.value } : item))} className="h-8" /></td>)}</tr>)}</tbody></table></div><div className="flex justify-end border-t border-slate-200 p-3"><Button type="button" onClick={saveSchedule} disabled={loading} className="h-9 bg-emerald-600 text-white">Save & choose members <ArrowRight className="size-4" /></Button></div></CardContent></Card>}
  {step === 3 && <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="border-b border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="text-sm font-bold">Choose members</CardTitle><p className="mt-1 text-[11px] text-slate-500">Search and select members to enroll in this scheme.</p></div><Badge variant="outline" className="w-fit border-emerald-200 bg-emerald-50 text-emerald-700">{selected.length} selected</Badge></div></CardHeader><CardContent className="p-4"><div className="relative mb-3 max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><Input value={memberSearch} onChange={(event) => setMemberSearch(event.target.value)} placeholder="Search name, mobile, or member code" className="h-9 border-slate-300 pl-9" /></div>{filteredMembers.length === 0 ? <div className="rounded-lg border border-dashed border-slate-300 px-4 py-8 text-center"><UsersRound className="mx-auto size-7 text-slate-400" /><p className="mt-2 text-xs font-bold text-slate-800">No members found</p><p className="mt-1 text-[10px] text-slate-500">Try another name, mobile number, or member code.</p></div> : <div className="grid gap-2 sm:grid-cols-2">{filteredMembers.map(member => <label key={member.id} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 ${selected.includes(member.id) ? "border-emerald-300 bg-emerald-50" : "border-slate-200"}`}><Checkbox checked={selected.includes(member.id)} onCheckedChange={() => setSelected(current => current.includes(member.id) ? current.filter(id => id !== member.id) : [...current, member.id])} /><div><p className="text-xs font-bold text-slate-950">{member.full_name}</p><p className="text-[10px] text-slate-500">{member.member_code} · {member.mobile_number}</p></div></label>)}</div>}<div className="mt-4 flex justify-end"><Button type="button" onClick={saveMembers} disabled={loading} className="h-9 bg-emerald-600 text-white">Save members <ArrowRight className="size-4" /></Button></div></CardContent></Card>}
  {step === 4 && group && <Card className="mx-auto max-w-xl border border-emerald-200 bg-white py-0 shadow-sm ring-0"><CardContent className="p-8 text-center"><span className="mx-auto flex size-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check className="size-6" /></span><h2 className="mt-4 text-lg font-bold text-slate-950">Scheme is ready</h2><p className="mt-2 text-xs text-slate-600">{group.scheme_name} has {schedule.length} installments and {selected.length} enrolled members.</p><Button type="button" onClick={() => router.push(`/dashboard/chits/${group.id}`)} className="mt-5 h-9 bg-emerald-600 text-white">View scheme details <ArrowRight className="size-4" /></Button></CardContent></Card>}</div>;
}
function Steps({ current }: { current: number }) { return <div className="grid grid-cols-4 gap-2">{[[WalletCards,"Scheme"],[CalendarRange,"Schedule"],[UsersRound,"Members"],[Check,"Review"]].map(([Icon,label], index) => { const done = current > index + 1; const active = current === index + 1; const C = Icon as typeof WalletCards; return <div key={label as string} className={`flex items-center gap-2 rounded-lg border px-3 py-2 ${active ? "border-emerald-300 bg-emerald-50" : "border-slate-200 bg-white"}`}><span className={`flex size-6 items-center justify-center rounded-full ${done || active ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{done ? <Check className="size-3.5" /> : <C className="size-3.5" />}</span><span className="hidden text-[11px] font-bold text-slate-700 sm:block">{label as string}</span></div>; })}</div>; }
function Field({ label, name, required, type = "text", min, max }: { label: string; name: string; required?: boolean; type?: string; min?: number; max?: number }) { return <div className="space-y-1.5"><Label htmlFor={name} className="text-xs font-semibold">{label}</Label><Input id={name} name={name} required={required} type={type} min={min} max={max} className="h-9" /></div>; }
