"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeIndianRupee, CalendarDays, Filter, Plus, ReceiptIndianRupee, WalletCards, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { authenticatedApiRequest } from "@/lib/api";

type Member = { member_id: number; member_code: string; full_name: string; mobile_number: string; status: string };
type Scheme = { id: number; group_code: string; scheme_name: string; members: Member[] };
type Advance = { id: number; group_id: number; group_code: string; scheme_name: string; member_id: number; member_code: string; member_name: string; mobile_number: string; receipt_number: string; amount: string; allocated_amount: string; available_amount: string; payment_date: string; payment_mode: string; reference_number: string | null; status: string; created_at: string };
const today = new Date().toISOString().slice(0, 10);

export default function AdvancePaymentsPage() {
  const [schemes, setSchemes] = useState<Scheme[]>([]); const [advances, setAdvances] = useState<Advance[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [schemeFilter, setSchemeFilter] = useState<string | null>(null); const [memberFilter, setMemberFilter] = useState<string | null>(null); const [statusFilter, setStatusFilter] = useState<string | null>(null); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("");
  const [open, setOpen] = useState(false); const [schemeId, setSchemeId] = useState<string | null>(null); const [memberId, setMemberId] = useState<string | null>(null); const [amount, setAmount] = useState(""); const [paymentDate, setPaymentDate] = useState(today); const [mode, setMode] = useState<string | null>("cash"); const [reference, setReference] = useState(""); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const [allocatingId, setAllocatingId] = useState<number | null>(null);
  const members = useMemo(() => { const map = new Map<number, Member>(); schemes.forEach(group => group.members.filter(member => member.status === "active").forEach(member => map.set(member.member_id, member))); return [...map.values()]; }, [schemes]);
  const selectedMembers = schemes.find(group => String(group.id) === schemeId)?.members.filter(member => member.status === "active") ?? [];
  async function load(filters = true) { setLoading(true); setError(""); try { const params = new URLSearchParams(); if (filters && schemeFilter) params.set("group_id", schemeFilter); if (filters && memberFilter) params.set("member_id", memberFilter); if (filters && statusFilter) params.set("payment_status", statusFilter); if (filters && dateFrom) params.set("date_from", dateFrom); if (filters && dateTo) params.set("date_to", dateTo); setAdvances(await authenticatedApiRequest<Advance[]>(`/api/v1/advance-payments?${params}`)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load advance payments."); } finally { setLoading(false); } }
  useEffect(() => { const timer = setTimeout(async () => { try { const [groups, rows] = await Promise.all([authenticatedApiRequest<Scheme[]>("/api/v1/chits"), authenticatedApiRequest<Advance[]>("/api/v1/advance-payments")]); setSchemes(groups); setAdvances(rows); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load advance payments."); } finally { setLoading(false); } }, 0); return () => clearTimeout(timer); }, []);
  async function create(event: FormEvent) { event.preventDefault(); if (!schemeId || !memberId || !mode) return; setSaving(true); setError(""); try { await authenticatedApiRequest<Advance>("/api/v1/advance-payments", { method: "POST", body: JSON.stringify({ group_id: Number(schemeId), member_id: Number(memberId), amount, payment_date: paymentDate, payment_mode: mode, reference_number: reference || null, notes: notes || null }) }); setOpen(false); setSchemeId(null); setMemberId(null); setAmount(""); setReference(""); setNotes(""); await load(false); } catch (err) { setError(err instanceof Error ? err.message : "Unable to record advance payment."); } finally { setSaving(false); } }
  async function allocate(id: number) { setAllocatingId(id); setError(""); try { await authenticatedApiRequest<Advance>(`/api/v1/advance-payments/${id}/allocate`, { method: "POST", body: JSON.stringify({ schedule_ids: null }) }); await load(false); } catch (err) { setError(err instanceof Error ? err.message : "Unable to allocate advance payment."); } finally { setAllocatingId(null); } }
  function submitFilters(event: FormEvent) { event.preventDefault(); void load(true); } function clearFilters() { setSchemeFilter(null); setMemberFilter(null); setStatusFilter(null); setDateFrom(""); setDateTo(""); setTimeout(() => void load(false), 0); }
  const received = advances.reduce((sum, row) => sum + Number(row.amount), 0); const allocated = advances.reduce((sum, row) => sum + Number(row.allocated_amount), 0); const available = advances.reduce((sum, row) => sum + Number(row.available_amount), 0);
  return <div className="mx-auto max-w-[1600px] space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Collections</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Advance payments</h1><p className="mt-1 text-[13px] text-slate-600">Hold member advances as a liability and allocate them to eligible installments.</p></div><Sheet open={open} onOpenChange={setOpen}><SheetTrigger render={<Button className="h-9 bg-emerald-600 text-white hover:bg-emerald-700" />}><Plus className="size-4" />Record advance</SheetTrigger><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Record advance payment</SheetTitle></SheetHeader><form onSubmit={create} className="space-y-4 px-4 pb-6"><ReadableSelect label="Scheme" value={schemeId} setValue={value => { setSchemeId(value); setMemberId(null); }} placeholder="Select scheme" items={schemes.map(group => ({ value: String(group.id), label: `${group.scheme_name} · ${group.group_code}` }))} /><ReadableSelect label="Member" value={memberId} setValue={setMemberId} placeholder={schemeId ? "Select enrolled member" : "Select scheme first"} items={selectedMembers.map(member => ({ value: String(member.member_id), label: `${member.full_name} · ${member.member_code}` }))} /><Field label="Advance amount" type="number" value={amount} setValue={setAmount} /><Field label="Payment date" type="date" value={paymentDate} setValue={setPaymentDate} /><ReadableSelect label="Payment mode" value={mode} setValue={setMode} placeholder="Select mode" items={["cash","upi","bank","cheque"].map(value => ({ value, label: value.toUpperCase() }))} /><Field label="Reference number" value={reference} setValue={setReference} required={false} /><Field label="Notes" value={notes} setValue={setNotes} required={false} /><Button type="submit" disabled={saving || !schemeId || !memberId || !amount} className="h-9 w-full bg-emerald-600 text-white hover:bg-emerald-700">{saving ? "Recording…" : "Record advance"}</Button></form></SheetContent></Sheet></div>
  <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="overflow-visible p-4"><div className="mb-3 flex items-center gap-2"><Filter className="size-4 text-emerald-700"/><CardTitle className="text-xs">Advance filters</CardTitle></div><form onSubmit={submitFilters} className="grid items-end gap-3 md:grid-cols-2 xl:grid-cols-[1fr_1fr_.8fr_150px_150px_auto]"><ReadableSelect label="Scheme" value={schemeFilter} setValue={setSchemeFilter} placeholder="All schemes" items={schemes.map(group => ({ value:String(group.id), label:`${group.scheme_name} · ${group.group_code}` }))}/><ReadableSelect label="Member" value={memberFilter} setValue={setMemberFilter} placeholder="All members" items={members.map(member => ({ value:String(member.member_id), label:`${member.full_name} · ${member.member_code}` }))}/><ReadableSelect label="Status" value={statusFilter} setValue={setStatusFilter} placeholder="All statuses" items={[{value:"available",label:"Available"},{value:"partially_allocated",label:"Partially allocated"},{value:"allocated",label:"Allocated"}]}/><Field label="From date" type="date" value={dateFrom} setValue={setDateFrom} required={false}/><Field label="To date" type="date" value={dateTo} setValue={setDateTo} required={false}/><div className="flex h-9 gap-2"><Button type="submit" className="h-9 bg-emerald-600 text-white">Apply</Button><Button type="button" variant="outline" size="icon" className="size-9" onClick={clearFilters}><X className="size-4"/></Button></div></form></CardContent></Card>
  {error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-3"><Stat icon={BadgeIndianRupee} label="Advance received" value={received}/><Stat icon={ReceiptIndianRupee} label="Allocated" value={allocated}/><Stat icon={WalletCards} label="Available balance" value={available}/></div>
  <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-200 bg-slate-50 p-4"><div><CardTitle className="text-sm">Advance register</CardTitle><p className="mt-1 text-[10px] text-slate-500">Original receipts and remaining balances are preserved.</p></div><Badge variant="outline">{advances.length} records</Badge></CardHeader><CardContent className="overflow-x-auto p-0">{loading ? <p className="p-10 text-center text-xs text-slate-500">Loading advances…</p> : advances.length === 0 ? <p className="p-10 text-center text-xs text-slate-500">No advance payments match these filters.</p> : <table className="w-full min-w-[1050px] text-xs"><thead className="bg-slate-50"><tr>{["Date","Receipt","Scheme","Member","Mode","Received","Allocated","Available","Status","Action"].map(label => <th key={label} className="px-4 py-3 text-left text-[10px] font-bold text-slate-700">{label}</th>)}</tr></thead><tbody>{advances.map(row => <tr key={row.id} className="border-t border-slate-100 hover:bg-emerald-50/50"><td className="px-4 py-3 font-semibold">{new Date(row.payment_date).toLocaleDateString("en-IN")}</td><td className="px-4 py-3 font-bold text-emerald-700">{row.receipt_number}</td><td className="px-4 py-3"><p className="font-bold text-slate-950">{row.scheme_name}</p><p className="text-[9px] text-slate-500">{row.group_code}</p></td><td className="px-4 py-3"><p className="font-bold text-slate-950">{row.member_name}</p><p className="text-[9px] text-slate-500">{row.member_code}</p></td><td className="px-4 py-3 uppercase">{row.payment_mode}</td><MoneyCell value={row.amount}/><MoneyCell value={row.allocated_amount}/><MoneyCell value={row.available_amount}/><td className="px-4 py-3"><Badge className={row.status === "allocated" ? "bg-slate-100 text-slate-700" : "bg-emerald-50 text-emerald-700"}>{row.status.replaceAll("_"," ")}</Badge></td><td className="px-4 py-3"><Button type="button" variant="outline" className="h-8 text-[11px]" disabled={Number(row.available_amount) <= 0 || allocatingId === row.id} onClick={() => void allocate(row.id)}>{allocatingId === row.id ? "Allocating…" : "Auto allocate"}</Button></td></tr>)}</tbody></table>}</CardContent></Card></div>;
}
function ReadableSelect({label,value,setValue,placeholder,items}:{label:string;value:string|null;setValue:(value:string|null)=>void;placeholder:string;items:{value:string;label:string}[]}) { const selected=items.find(item=>item.value===value)?.label; return <div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">{label}</Label><Select value={value} onValueChange={setValue}><SelectTrigger className="h-9 w-full"><SelectValue>{selected??placeholder}</SelectValue></SelectTrigger><SelectContent>{items.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>; }
function Field({label,value,setValue,type="text",required=true}:{label:string;value:string;setValue:(value:string)=>void;type?:string;required?:boolean}) { return <div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">{label}</Label><Input type={type} value={value} onChange={event=>setValue(event.target.value)} required={required} min={type==="number"?"0.01":undefined} step={type==="number"?"0.01":undefined} className="h-9"/></div>; }
function Stat({icon:Icon,label,value}:{icon:typeof CalendarDays;label:string;value:number}) { return <Card className="border border-slate-200 bg-white py-0 ring-0"><CardContent className="flex items-center gap-3 p-4"><span className="flex size-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700"><Icon className="size-5"/></span><div><p className="text-xs font-semibold text-slate-600">{label}</p><p className="text-lg font-bold text-slate-950">₹{value.toLocaleString("en-IN")}</p></div></CardContent></Card>; }
function MoneyCell({value}:{value:string}) { return <td className="px-4 py-3 font-bold text-slate-950">₹{Number(value).toLocaleString("en-IN")}</td>; }
