import { useEffect, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { authRequest } from "./api";
import { colors } from "./theme";
import { MultiPicker } from "./MultiPicker";
import { SearchPicker } from "./SearchPicker";
type R=Record<string,unknown>;
export function AgentAssignmentAction({row,onDone}:{row:R;onDone:()=>Promise<void>}){const[groups,setGroups]=useState<number[]>([]);const[enrollments,setEnrollments]=useState<number[]>([]);const[initialGroups,setInitialGroups]=useState<number[]>([]);const[initialEnrollments,setInitialEnrollments]=useState<number[]>([]);const[groupNames,setGroupNames]=useState<string[]>([]);const[memberNames,setMemberNames]=useState<string[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{void load();},[row.id]);async function load(){setLoading(true);try{const saved=await authRequest<{group_ids:number[];enrollment_ids:number[];groups:{scheme_name:string}[];members:{member_name:string;scheme_name:string}[]}>(`/api/v1/admin/collection-agents/${row.id}/assignments`);setGroups(saved.group_ids);setEnrollments(saved.enrollment_ids);setInitialGroups(saved.group_ids);setInitialEnrollments(saved.enrollment_ids);setGroupNames(saved.groups.map(item=>item.scheme_name));setMemberNames(saved.members.map(item=>`${item.member_name} · ${item.scheme_name}`));}catch(error){Alert.alert("Unable to load assignments",error instanceof Error?error.message:"Request failed");}finally{setLoading(false);}}const changed=JSON.stringify([...groups].sort((a,b)=>a-b))!==JSON.stringify([...initialGroups].sort((a,b)=>a-b))||JSON.stringify([...enrollments].sort((a,b)=>a-b))!==JSON.stringify([...initialEnrollments].sort((a,b)=>a-b));async function save(){if(!changed)return;try{await authRequest(`/api/v1/admin/collection-agents/${row.id}/assignments`,{method:"PUT",body:JSON.stringify({group_ids:groups,enrollment_ids:enrollments})});setInitialGroups(groups);setInitialEnrollments(enrollments);Alert.alert("Saved","Agent assignments updated.");await onDone();}catch(error){Alert.alert("Unable to save",error instanceof Error?error.message:"Request failed");}}return <View style={styles.box}><Text style={styles.title}>Assignments</Text><View style={styles.assignmentSummary}><Text style={styles.assignmentTitle}>{loading?"Loading current assignments…":"Currently assigned"}</Text>{!loading?<><Text style={styles.assignmentLine}>{groupNames.length?`Schemes: ${groupNames.join(", ")}`:"Schemes: None"}</Text><Text style={styles.assignmentLine}>{memberNames.length?`Members: ${memberNames.join(", ")}`:"Members: None"}</Text></>:null}</View><MultiPicker label="Assigned schemes" source="schemes" values={groups} onChange={setGroups}/><MultiPicker label="Assigned members" source="enrollments" values={enrollments} onChange={setEnrollments}/><Pressable disabled={loading||!changed} onPress={()=>void save()} style={[styles.action,(loading||!changed)&&styles.actionDisabled]}><Text style={[styles.actionText,(loading||!changed)&&styles.actionTextDisabled]}>{changed?"Save assignment changes":"Assignments already up to date"}</Text></Pressable></View>}
export function PayrollDaysAction({row,onDone}:{row:R;onDone:()=>Promise<void>}){const[itemId,setItemId]=useState("");const[payable,setPayable]=useState("");const[lop,setLop]=useState("0");async function save(){try{await authRequest(`/api/v1/payroll/runs/${row.id}/items/${itemId}/days`,{method:"PUT",body:JSON.stringify({payable_days:Number(payable),lop_days:Number(lop)})});Alert.alert("Updated","Payroll days recalculated.");await onDone();}catch(error){Alert.alert("Unable to update",error instanceof Error?error.message:"Request failed");}}return <View style={styles.box}><Text style={styles.title}>Payable-day adjustment</Text><SearchPicker label="Payroll employee" value={itemId} onChange={setItemId} source="payrollItems" groupId={String(row.id)}/><Input value={payable} setValue={setPayable} placeholder="Payable days"/><Input value={lop} setValue={setLop} placeholder="Loss-of-pay days"/><Action label="Recalculate payroll" onPress={()=>void save()}/></View>}
function Input({value,setValue,placeholder}:{value:string;setValue:(value:string)=>void;placeholder:string}){return <TextInput value={value} onChangeText={setValue} keyboardType="numbers-and-punctuation" placeholder={placeholder} style={styles.input}/>}function Action({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.action}><Text style={styles.actionText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({box:{gap:7,marginTop:9,paddingTop:9,borderTopWidth:1,borderTopColor:colors.border},title:{fontSize:10,fontWeight:"900",color:colors.slate700},assignmentSummary:{backgroundColor:"#ecfdf5",borderWidth:1,borderColor:"#a7f3d0",padding:9,borderRadius:8},assignmentTitle:{fontSize:9.5,fontWeight:"900",color:colors.emeraldDark},assignmentLine:{fontSize:9.5,lineHeight:14,color:colors.slate700,marginTop:3},input:{height:36,borderWidth:1,borderColor:"#cbd5e1",borderRadius:8,paddingHorizontal:9,fontSize:11,color:colors.slate950},action:{height:37,borderRadius:9,backgroundColor:colors.emerald,alignItems:"center",justifyContent:"center"},actionDisabled:{backgroundColor:"#e2e8f0"},actionText:{fontSize:10.5,fontWeight:"900",color:colors.white},actionTextDisabled:{color:colors.slate500}});
