import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { authRequest } from "./api";
import { colors } from "./theme";
import { SearchPicker } from "./SearchPicker";
type R=Record<string,unknown>;
export function AuctionActions({auction,onDone}:{auction:R;onDone:()=>Promise<void>}){const[bidder,setBidder]=useState("");const[bid,setBid]=useState("");const[discount,setDiscount]=useState("");const[reason,setReason]=useState("");async function addBid(){try{await authRequest(`/api/v1/chits/${auction.group_id}/auctions/${auction.id}/bids`,{method:"POST",body:JSON.stringify({bidder_member_id:Number(bidder),bid_amount:Number(bid),discount_amount:Number(discount)})});Alert.alert("Added","Auction bid recorded.");await onDone();}catch(error){Alert.alert("Unable to add bid",error instanceof Error?error.message:"Request failed");}}async function cancel(){try{await authRequest(`/api/v1/chits/${auction.group_id}/auctions/${auction.id}/cancel`,{method:"POST",body:JSON.stringify({reason})});Alert.alert("Cancelled","Auction cancelled.");await onDone();}catch(error){Alert.alert("Unable to cancel",error instanceof Error?error.message:"Request failed");}}return <View style={styles.box}><Text style={styles.title}>Bid register</Text><SearchPicker label="Bidder member" value={bidder} onChange={setBidder} source="enrolledMembers" groupId={String(auction.group_id)}/><Input value={bid} setValue={setBid} placeholder="Bid amount"/><Input value={discount} setValue={setDiscount} placeholder="Discount amount"/><Action label="Record bid" onPress={()=>void addBid()}/>{["pending","approved"].includes(String(auction.status))?<><Text style={styles.title}>Cancel auction</Text><Input value={reason} setValue={setReason} placeholder="Mandatory cancellation reason"/><Action label="Cancel auction" danger onPress={()=>void cancel()}/></>:null}</View>}
function Input({value,setValue,placeholder}:{value:string;setValue:(value:string)=>void;placeholder:string}){return <TextInput value={value} onChangeText={setValue} keyboardType={placeholder.includes("amount")||placeholder.includes("ID")?"numeric":"default"} placeholder={placeholder} style={styles.input}/>}function Action({label,onPress,danger=false}:{label:string;onPress:()=>void;danger?:boolean}){return <Pressable onPress={onPress} style={[styles.action,danger&&styles.danger]}><Text style={[styles.actionText,danger&&styles.dangerText]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({box:{gap:7,marginTop:9,paddingTop:9,borderTopWidth:1,borderTopColor:colors.border},title:{fontSize:10,fontWeight:"900",color:colors.slate700,marginTop:2},input:{height:36,borderWidth:1,borderColor:"#cbd5e1",borderRadius:8,paddingHorizontal:9,fontSize:11,color:colors.slate950},action:{height:37,borderRadius:9,backgroundColor:colors.emerald,alignItems:"center",justifyContent:"center"},actionText:{fontSize:10.5,fontWeight:"900",color:colors.white},danger:{backgroundColor:"#fef2f2",borderWidth:1,borderColor:"#fecaca"},dangerText:{color:colors.red}});
