import { useEffect, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { authRequest } from "./api";
import { colors } from "./theme";
import { MultiPicker } from "./MultiPicker";
type R=Record<string,unknown>;
export function ChitActions({group,onDone}:{group:R;onDone:()=>Promise<void>}){const currentMembers=((group.members as R[]|undefined)??[]).filter(item=>item.status==="active").map(item=>Number(item.member_id));const[memberIds,setMemberIds]=useState<number[]>(currentMembers);useEffect(()=>setMemberIds(currentMembers),[group.id,JSON.stringify(currentMembers)]);const[balance,setBalance]=useState("");const[reason,setReason]=useState("");async function action(label:string,work:()=>Promise<unknown>){try{await work();Alert.alert("Completed",label);await onDone();}catch(error){Alert.alert("Unable to complete",error instanceof Error?error.message:"Request failed");}}async function enroll(){await action("Member enrollment updated",()=>authRequest(`/api/v1/chits/${group.id}/members`,{method:"PUT",body:JSON.stringify({member_ids:memberIds})}));}async function close(){await action("Scheme closed",()=>authRequest(`/api/v1/chits/${group.id}/close`,{method:"POST",body:JSON.stringify({actual_closing_balance:Number(balance),variance_reason:reason||null})}));}return <View style={styles.box}><Text style={styles.title}>Scheme management</Text><Text style={styles.hint}>Current active members are preselected. Changes replace the active enrollment set.</Text><MultiPicker label="Active members" source="members" values={memberIds} onChange={setMemberIds}/><Action label="Update enrollment" onPress={()=>void enroll()}/><Text style={styles.hint}>Closing requires zero outstanding balance and no pending auctions.</Text><Input value={balance} setValue={setBalance} placeholder="Actual closing balance"/><Input value={reason} setValue={setReason} placeholder="Variance reason if required"/><Action label="Run final closure" onPress={()=>void close()} danger/></View>}
function Input({value,setValue,placeholder}:{value:string;setValue:(value:string)=>void;placeholder:string}){return <TextInput value={value} onChangeText={setValue} placeholder={placeholder} style={styles.input}/>}function Action({label,onPress,danger=false}:{label:string;onPress:()=>void;danger?:boolean}){return <Pressable onPress={onPress} style={[styles.action,danger&&styles.danger]}><Text style={[styles.actionText,danger&&styles.dangerText]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({box:{gap:8,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:13,marginTop:11},title:{fontSize:12.5,fontWeight:"900",color:colors.slate950},hint:{fontSize:9.5,lineHeight:14,color:colors.slate500},input:{height:40,borderWidth:1,borderColor:"#cbd5e1",borderRadius:9,paddingHorizontal:10,fontSize:11.5,color:colors.slate950},action:{height:39,borderRadius:9,backgroundColor:colors.emerald,alignItems:"center",justifyContent:"center"},actionText:{fontSize:10.5,fontWeight:"900",color:colors.white},danger:{backgroundColor:"#fef2f2",borderWidth:1,borderColor:"#fecaca"},dangerText:{color:colors.red}});
