import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as SecureStore from "expo-secure-store";
import { ACCESS_KEY, API_URL, authRequest } from "./api";
import { colors } from "./theme";
type R=Record<string,unknown>;
export function EmployeeActions({employee,onDone}:{employee:R;onDone:()=>Promise<void>}){const[effective,setEffective]=useState(new Date().toISOString().slice(0,10));const[basic,setBasic]=useState("");const[hra,setHra]=useState("0");const[allowances,setAllowances]=useState("0");const[documentType,setDocumentType]=useState("photo");async function salary(){try{const gross=Number(basic)+Number(hra)+Number(allowances);await authRequest(`/api/v1/employees/${employee.id}/salary`,{method:"POST",body:JSON.stringify({effective_from:effective,annual_ctc:gross*12,basic:Number(basic),hra:Number(hra),allowances:Number(allowances),incentives:0,employee_pf:0,employee_esi:0,professional_tax:0,tds:0,other_deductions:0,notes:"Added from Owner app"})});Alert.alert("Added","Salary structure created.");await onDone();}catch(error){Alert.alert("Unable to add salary",error instanceof Error?error.message:"Request failed");}}async function upload(){try{const result=await DocumentPicker.getDocumentAsync({type:["application/pdf","image/jpeg","image/png"],copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];const data=new FormData();data.append("document_type",documentType);data.append("file",{uri:asset.uri,name:asset.name,mimeType:asset.mimeType??"application/octet-stream"} as never);const token=await SecureStore.getItemAsync(ACCESS_KEY);const response=await fetch(`${API_URL}/api/v1/employees/${employee.id}/documents`,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:data});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail??"Upload failed");Alert.alert("Uploaded","Employee evidence uploaded.");await onDone();}catch(error){Alert.alert("Unable to upload",error instanceof Error?error.message:"Request failed");}}return <View style={styles.box}><Text style={styles.title}>Salary structure</Text><Input value={effective} setValue={setEffective} placeholder="Effective date"/><Input value={basic} setValue={setBasic} placeholder="Monthly basic"/><Input value={hra} setValue={setHra} placeholder="Monthly HRA"/><Input value={allowances} setValue={setAllowances} placeholder="Monthly allowances"/><Action label="Add salary structure" onPress={()=>void salary()}/><Text style={styles.title}>Employee evidence</Text><Input value={documentType} setValue={setDocumentType} placeholder="photo / aadhaar / pan / bank_proof"/><Action label="Choose and upload document" onPress={()=>void upload()}/></View>}
function Input({value,setValue,placeholder}:{value:string;setValue:(value:string)=>void;placeholder:string}){return <TextInput value={value} onChangeText={setValue} placeholder={placeholder} style={styles.input}/>}function Action({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.action}><Text style={styles.actionText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({box:{gap:8,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:13,marginTop:11},title:{fontSize:10.5,fontWeight:"900",color:colors.slate700,marginTop:3},input:{height:39,borderWidth:1,borderColor:"#cbd5e1",borderRadius:9,paddingHorizontal:10,fontSize:11.5,color:colors.slate950},action:{height:39,borderRadius:9,backgroundColor:colors.emerald,alignItems:"center",justifyContent:"center"},actionText:{fontSize:10.5,fontWeight:"900",color:colors.white}});
