import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { Empty } from "./components";
import { modules } from "./modules";
import { colors } from "./theme";
import { Screen } from "./types";

type RecordValue=Record<string,unknown>;
const first=(row:RecordValue,keys:string[])=>{for(const key of keys){const value=row[key];if(value!==null&&value!==undefined&&value!=="")return String(value);}return "—";};
const money=(value:unknown)=>`₹${Number(value??0).toLocaleString("en-IN")}`;
export function ModuleScreen({screen,data,refreshing,onRefresh,onSelect}:{screen:Exclude<Screen,"dashboard">;data:unknown;refreshing:boolean;onRefresh:()=>void;onSelect:(record:RecordValue)=>void}){const config=modules[screen];const root=(data??{}) as RecordValue;const raw=config.collectionKey?root[config.collectionKey]:data;const rows=Array.isArray(raw)?raw as RecordValue[]:[root];return <ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[colors.emerald]} tintColor={colors.emerald}/>}><View style={styles.intro}><Text style={styles.eyebrow}>OWNER MONITORING</Text><Text style={styles.title}>{config.label}</Text><Text style={styles.subtitle}>{config.subtitle}</Text></View>{screen==="reports"&&<View style={styles.stats}><Mini label="INFLOW" value={money(root.total_inflow)}/><Mini label="OUTFLOW" value={money(root.total_outflow)}/><Mini label="NET FLOW" value={money(root.net_cash_flow)}/><Mini label="RECORDS" value={first(root,["transaction_count"])}/></View>}{screen==="collections"&&<View style={styles.stats}><Mini label="RECEIVED" value={money(root.total_received_amount)}/><Mini label="NET" value={money(root.net_received_amount)}/><Mini label="REFUNDED" value={money(root.total_refunded_amount)}/><Mini label="RECORDS" value={first(root,["total_transactions"])}/></View>}{rows.length===0||rows.length===1&&Object.keys(rows[0]??{}).length===0?<Empty message={`No ${config.label.toLowerCase()} records available.`}/>:rows.map((row,index)=><Pressable key={first(row,["id","payment_id","employee_id","member_code","group_code","receipt_number"])+index} onPress={()=>onSelect(row)}><RecordCard screen={screen} row={row}/></Pressable>)}</ScrollView>}
function RecordCard({screen,row}:{screen:Exclude<Screen,"dashboard">;row:RecordValue}){const title=screen==="members"?first(row,["full_name","member_name"]):screen==="chits"?first(row,["scheme_name"]):screen==="agents"||screen==="tracking"?first(row,["employee_name"]):screen==="employees"?first(row,["full_name","employee_name"]):screen==="users"?first(row,["employee_name","login_id"]):screen==="company"?first(row,["name","legal_name"]):screen==="audit"?first(row,["description","action"]):first(row,["member_name","scheme_name","receipt_number","voucher_number","employee_name","description","payroll_month"]);const code=first(row,["member_code","group_code","employee_code","login_id","company_code","receipt_number","voucher_number","action"]);const status=first(row,["status","kyc_status","shift_status","is_active"]);const detail=screen==="tracking"?`${first(row,["last_latitude"])} · ${first(row,["last_longitude"])}`:screen==="members"?first(row,["mobile_number"]):screen==="chits"?`${first(row,["duration_months"])} months · ${money(row.scheme_amount)}`:screen==="payroll"?`${first(row,["payroll_month"])}/${first(row,["payroll_year"])} · ${money(row.total_net_salary)}`:screen==="audit"?`${first(row,["actor_email"])} · ${first(row,["created_at"])}`:first(row,["mobile_number","payment_mode","department","role","email","reference_number","transaction_date","payment_date"]);const amount=row.amount??row.net_received_amount??row.allocated_amount??row.net_payout_amount;return <View style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{title[0]?.toUpperCase()??"Z"}</Text></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={styles.cardTitle}>{title}</Text><Text numberOfLines={1} style={styles.cardCode}>{code}</Text><Text numberOfLines={2} style={styles.cardDetail}>{detail}</Text></View><View style={styles.right}>{amount!==undefined&&<Text style={styles.amount}>{money(amount)}</Text>}<Text style={styles.status}>{status.replaceAll("_"," ").toUpperCase()}</Text></View></View>}
function Mini({label,value}:{label:string;value:string}){return <View style={styles.mini}><Text style={styles.miniLabel}>{label}</Text><Text style={styles.miniValue}>{value}</Text></View>}
const styles=StyleSheet.create({scroll:{padding:15,paddingBottom:40},intro:{marginBottom:13},eyebrow:{fontSize:8.5,fontWeight:"900",letterSpacing:1.2,color:colors.emeraldDark},title:{fontSize:23,fontWeight:"900",color:colors.slate950,marginTop:4},subtitle:{fontSize:11.5,color:colors.slate600,marginTop:4},stats:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:12},mini:{width:"48.7%",backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12},miniLabel:{fontSize:8,fontWeight:"900",letterSpacing:.7,color:colors.slate500},miniValue:{fontSize:15,fontWeight:"900",color:colors.slate950,marginTop:6},card:{flexDirection:"row",alignItems:"center",gap:10,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:13,padding:12,marginBottom:8},avatar:{width:39,height:39,borderRadius:12,backgroundColor:colors.emeraldSoft,alignItems:"center",justifyContent:"center"},avatarText:{fontSize:15,fontWeight:"900",color:colors.emeraldDark},cardTitle:{fontSize:12.5,fontWeight:"900",color:colors.slate950},cardCode:{fontSize:9.5,fontWeight:"700",color:colors.emeraldDark,marginTop:2},cardDetail:{fontSize:9.5,lineHeight:14,color:colors.slate500,marginTop:3},right:{alignItems:"flex-end",gap:5,maxWidth:105},amount:{fontSize:12.5,fontWeight:"900",color:colors.emeraldDark},status:{fontSize:7.5,fontWeight:"900",color:colors.slate600,backgroundColor:"#f1f5f9",paddingHorizontal:6,paddingVertical:4,borderRadius:6}});
