import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import { ACCESS_KEY, API_URL, authRequest } from "./api";
import * as SecureStore from "expo-secure-store";
import { colors } from "./theme";
type R=Record<string,unknown>;
async function multipart(path:string,values:Record<string,string>,fileField:string){const selected=await DocumentPicker.getDocumentAsync({type:["application/pdf","image/jpeg","image/png"],copyToCacheDirectory:true});if(selected.canceled)throw new Error("Select the required proof document");const data=new FormData();Object.entries(values).forEach(([key,value])=>data.append(key,value));const asset=selected.assets[0];data.append(fileField,{uri:asset.uri,name:asset.name,mimeType:asset.mimeType??"application/octet-stream"} as never);const token=await SecureStore.getItemAsync(ACCESS_KEY);const response=await fetch(`${API_URL}${path}`,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:data});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail??"Upload failed");return body;}
export function AuctionPaymentAction({row,onDone}:{row:R;onDone:()=>Promise<void>}){const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[mode,setMode]=useState("bank");const[reference,setReference]=useState("");async function pay(){try{await multipart(`/api/v1/chits/${row.group_id}/auctions/${row.id}/pay`,{payout_date:date,payout_mode:mode,payout_reference_number:reference,payout_verified:"true"},"settlement_proof");Alert.alert("Paid","Auction payout verified and voucher posted.");await onDone();}catch(error){Alert.alert("Unable to pay",error instanceof Error?error.message:"Request failed");}}return <View style={styles.box}><Text style={styles.title}>Payout verification</Text><Input label="Payout date" value={date} setValue={setDate}/><Input label="Mode" value={mode} setValue={setMode}/><Input label="Reference" value={reference} setValue={setReference}/><Action label="Select proof and mark paid" onPress={()=>void pay()}/></View>}
export function PayrollPaymentAction({row,onDone}:{row:R;onDone:()=>Promise<void>}){const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[mode,setMode]=useState("bank");const[reference,setReference]=useState("");async function pay(){try{await multipart(`/api/v1/payroll/runs/${row.id}/pay`,{payment_date:date,payment_mode:mode,payment_reference_number:reference},"payment_proof");Alert.alert("Paid","Payroll payment and proof recorded.");await onDone();}catch(error){Alert.alert("Unable to pay",error instanceof Error?error.message:"Request failed");}}return <View style={styles.box}><Text style={styles.title}>Payroll payment</Text><Input label="Payment date" value={date} setValue={setDate}/><Input label="Mode" value={mode} setValue={setMode}/><Input label="Reference" value={reference} setValue={setReference}/><Action label="Select proof and mark paid" onPress={()=>void pay()}/></View>}
export function UserPasswordAction({row,onDone}:{row:R;onDone:()=>Promise<void>}){const[password,setPassword]=useState("");async function reset(){try{await authRequest(`/api/v1/admin/users/${row.id}/password`,{method:"PUT",body:JSON.stringify({password})});Alert.alert("Updated","User password reset.");setPassword("");await onDone();}catch(error){Alert.alert("Unable to reset",error instanceof Error?error.message:"Request failed");}}return <View style={styles.box}><Text style={styles.title}>Reset user password</Text><Input label="New temporary password" value={password} setValue={setPassword} secure/><Action label="Reset password" onPress={()=>void reset()}/></View>}
function Input({label,value,setValue,secure=false}:{label:string;value:string;setValue:(value:string)=>void;secure?:boolean}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={setValue} secureTextEntry={secure} style={styles.input}/></View>}
function Action({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.action}><Text style={styles.actionText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({box:{marginTop:10,paddingTop:10,borderTopWidth:1,borderTopColor:colors.border,gap:8},title:{fontSize:10,fontWeight:"900",color:colors.slate700},field:{gap:4},label:{fontSize:8,fontWeight:"900",textTransform:"uppercase",color:colors.slate500},input:{height:36,borderWidth:1,borderColor:"#cbd5e1",borderRadius:8,paddingHorizontal:9,fontSize:11.5,color:colors.slate950},action:{height:38,borderRadius:9,backgroundColor:colors.emerald,alignItems:"center",justifyContent:"center"},actionText:{fontSize:10.5,fontWeight:"900",color:colors.white}});
