import { useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { authRequest, clearTokens } from "./api";
import { colors } from "./theme";
import { SecurityActions } from "./SecurityActions";
import { CommunicationSettingsAction } from "./CommunicationSettingsAction";

type Security={email:string;mfa_enabled:boolean;mfa_enabled_at:string|null;recovery_codes_remaining:number;active_sessions:number;password_updated_at:string};type Session={id:number;ip_address:string|null;user_agent:string|null;created_at:string;expires_at:string};
export function SecurityScreen({status,sessions,onRefresh,onSignedOut}:{status:Security;sessions:Session[];onRefresh:()=>Promise<void>;onSignedOut:()=>void}){const[refreshing,setRefreshing]=useState(false);async function refresh(){setRefreshing(true);try{await onRefresh();}finally{setRefreshing(false);}}async function revoke(id:number){await authRequest(`/api/v1/auth/sessions/${id}`,{method:"DELETE"});await refresh();}async function revokeAll(){await authRequest("/api/v1/auth/sessions/revoke-all",{method:"POST"});await clearTokens();onSignedOut();}return <ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} colors={[colors.emerald]}/>}><Text style={styles.eyebrow}>ACCOUNT PROTECTION</Text><Text style={styles.title}>Security</Text><Text style={styles.subtitle}>{status.email}</Text><View style={styles.stats}><Stat label="TWO-FACTOR" value={status.mfa_enabled?"ENABLED":"NOT ENABLED"} secure={status.mfa_enabled}/><Stat label="SESSIONS" value={String(status.active_sessions)} secure/><Stat label="RECOVERY CODES" value={String(status.recovery_codes_remaining)} secure={status.recovery_codes_remaining>0}/></View><View style={styles.card}><Text style={styles.cardTitle}>Authenticator protection</Text><Text style={styles.body}>{status.mfa_enabled?`Enabled ${status.mfa_enabled_at?new Date(status.mfa_enabled_at).toLocaleString("en-IN"):""}. Recovery codes can be regenerated in the web console.`:"Two-factor authentication is not enabled. Set it up in the web Security page before handling sensitive approvals."}</Text></View><CommunicationSettingsAction/><SecurityActions mfaEnabled={status.mfa_enabled} onDone={onRefresh} onSignedOut={onSignedOut}/><View style={styles.section}><View><Text style={styles.sectionTitle}>Active sessions</Text><Text style={styles.sectionSub}>Revoke unknown devices immediately.</Text></View><Pressable style={styles.revokeAll} onPress={revokeAll}><Text style={styles.revokeAllText}>Revoke all</Text></Pressable></View>{sessions.map(item=><View key={item.id} style={styles.session}><View style={styles.device}><Text style={styles.deviceText}>▣</Text></View><View style={{flex:1}}><Text style={styles.sessionTitle}>{item.user_agent?.includes("Mobile")?"Mobile device":"Web session"}</Text><Text style={styles.meta}>{item.ip_address??"Unknown IP"}</Text><Text style={styles.meta}>Signed in {new Date(item.created_at).toLocaleString("en-IN")}</Text></View><Pressable style={styles.revoke} onPress={()=>void revoke(item.id)}><Text style={styles.revokeText}>Revoke</Text></Pressable></View>)}</ScrollView>}
function Stat({label,value,secure}:{label:string;value:string;secure:boolean}){return <View style={[styles.stat,secure&&styles.statSecure]}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>}
const styles=StyleSheet.create({scroll:{padding:15,paddingBottom:40},eyebrow:{fontSize:8.5,fontWeight:"900",letterSpacing:1.2,color:colors.emeraldDark},title:{fontSize:23,fontWeight:"900",color:colors.slate950,marginTop:4},subtitle:{fontSize:11,color:colors.slate600,marginTop:4},stats:{flexDirection:"row",gap:7,marginTop:14},stat:{flex:1,borderRadius:12,padding:11,backgroundColor:"#fffbeb",borderWidth:1,borderColor:"#fde68a"},statSecure:{backgroundColor:"#ecfdf5",borderColor:"#a7f3d0"},statLabel:{fontSize:7,fontWeight:"900",color:colors.slate500},statValue:{fontSize:11,fontWeight:"900",color:colors.slate950,marginTop:6},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:14,marginTop:12},cardTitle:{fontSize:13,fontWeight:"900",color:colors.slate950},body:{fontSize:11,lineHeight:18,color:colors.slate600,marginTop:7},section:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:20,marginBottom:9},sectionTitle:{fontSize:14,fontWeight:"900",color:colors.slate950},sectionSub:{fontSize:9.5,color:colors.slate500,marginTop:3},revokeAll:{height:34,paddingHorizontal:11,borderRadius:9,borderWidth:1,borderColor:"#fecaca",alignItems:"center",justifyContent:"center"},revokeAllText:{fontSize:10,fontWeight:"900",color:colors.red},session:{flexDirection:"row",alignItems:"center",gap:10,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:13,padding:12,marginBottom:8},device:{width:38,height:38,borderRadius:11,backgroundColor:"#f1f5f9",alignItems:"center",justifyContent:"center"},deviceText:{fontSize:16,color:colors.slate700},sessionTitle:{fontSize:12,fontWeight:"900",color:colors.slate950},meta:{fontSize:9,color:colors.slate500,marginTop:3},revoke:{height:31,paddingHorizontal:9,borderRadius:8,borderWidth:1,borderColor:"#fecaca",justifyContent:"center"},revokeText:{fontSize:9.5,fontWeight:"900",color:colors.red}});
