"use client";

import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import { Building2, ImagePlus, Mail, MapPin, Pencil, Phone, Plus, Store, Trash2, UserRound } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { API_URL, ApiRequestError, authenticatedApiRequest, getResponseError } from "@/lib/api";

type Address = { address_line_1: string; address_line_2: string | null; locality: string | null; city: string; state: string; postal_code: string; country: string; landmark?: string | null };
type Company = { company_code: string; name: string; legal_name: string | null; mobile_number: string; email: string; gstin: string | null; pan: string | null; website: string | null; logo_url: string | null; addresses: Address[] };
type Branch = { id: number; branch_code: string; name: string; mobile_number: string | null; email: string | null; manager_name: string | null; address_line_1: string; address_line_2: string | null; locality: string | null; city: string; state: string; postal_code: string; country: string; landmark: string | null; is_active: boolean };
export default function CompanyProfilePage() {
  const [company, setCompany] = useState<Company | null>(null); const [branches, setBranches] = useState<Branch[]>([]); const [editing, setEditing] = useState<Branch | null>(null); const [open, setOpen] = useState(false); const [companyEditOpen, setCompanyEditOpen] = useState(false); const [logo, setLogo] = useState<File | null>(null); const [error, setError] = useState("");
  async function load() { const [companyData, branchData] = await Promise.all([authenticatedApiRequest<Company>("/api/v1/companies/me"), authenticatedApiRequest<Branch[]>("/api/v1/branches")]); setCompany(companyData); setBranches(branchData); }
  useEffect(() => { const timer = setTimeout(() => void load().catch(err => { if (err instanceof ApiRequestError && err.status === 401) { localStorage.removeItem("zchit_access_token"); window.location.replace("/login"); } else setError(err instanceof Error ? err.message : "Unable to load company."); }), 0); return () => clearTimeout(timer); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const optional = (name: string) => String(data.get(name) ?? "").trim() || null; const payload = { name: data.get("name"), mobile_number: optional("mobile_number"), email: optional("email"), manager_name: optional("manager_name"), address_line_1: data.get("address_line_1"), address_line_2: optional("address_line_2"), locality: optional("locality"), city: data.get("city"), state: data.get("state"), postal_code: data.get("postal_code"), country: "India", landmark: optional("landmark"), ...(editing ? { is_active: editing.is_active } : {}) }; try { await authenticatedApiRequest(editing ? `/api/v1/branches/${editing.id}` : "/api/v1/branches", { method: editing ? "PUT" : "POST", body: JSON.stringify(payload) }); setOpen(false); setEditing(null); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save branch."); } }
  async function remove(id: number) { try { await authenticatedApiRequest(`/api/v1/branches/${id}`, { method: "DELETE" }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to delete branch."); } }
  if (error && !company) return <div className="mx-auto max-w-3xl rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>;
  if (!company) return <p className="p-8 text-center text-sm text-slate-500">Loading company profile…</p>;
  const address = company.addresses[0]; return <div className="mx-auto max-w-[1400px] space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Organization</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Company profile</h1><p className="mt-1 text-[13px] text-slate-600">Manage company identity and operational branches.</p></div><div className="flex flex-wrap gap-2"><Sheet open={companyEditOpen} onOpenChange={(value) => { setCompanyEditOpen(value); if (!value) setLogo(null); }}><SheetTrigger render={<Button variant="outline" className="h-9" />}><Pencil className="size-4" />Edit company</SheetTrigger><CompanyForm key={`${company.company_code}:${company.name}:${company.mobile_number}:${company.email}:${address?.address_line_1 ?? ""}`} company={company} logo={logo} setLogo={setLogo} onSubmit={saveCompany} /></Sheet><Sheet open={open} onOpenChange={(value) => { setOpen(value); if (!value) setEditing(null); }}><SheetTrigger render={<Button className="h-9 bg-emerald-600 text-white" />} onClick={() => setEditing(null)}><Plus className="size-4" />Create branch</SheetTrigger><BranchForm key={editing?.id ?? "new"} branch={editing} onSubmit={save} /></Sheet></div></div>{error && <p className="rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}
  <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_.8fr]"><div><div className="flex items-center gap-3">{company.logo_url ? <Image src={company.logo_url} alt={`${company.name} logo`} width={48} height={48} unoptimized className="size-12 rounded-xl border border-slate-200 object-contain" /> : <span className="flex size-11 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700"><Building2 className="size-5" /></span>}<div><h2 className="text-lg font-bold text-slate-950">{company.name}</h2><p className="text-[10px] font-bold text-emerald-700">{company.company_code}</p></div></div><p className="mt-4 text-xs text-slate-600">{company.legal_name ?? company.name}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-600"><span className="flex items-center gap-1.5"><Phone className="size-3.5" />{company.mobile_number}</span><span className="flex items-center gap-1.5"><Mail className="size-3.5" />{company.email}</span></div></div><div className="rounded-lg border border-slate-200 bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Registered office</p>{address && <p className="mt-2 text-xs leading-5 text-slate-700">{address.address_line_1}{address.address_line_2 && `, ${address.address_line_2}`}<br />{address.city}, {address.state} – {address.postal_code}</p>}<div className="mt-3 flex gap-2">{company.gstin && <Badge variant="outline">GST {company.gstin}</Badge>}{company.pan && <Badge variant="outline">PAN {company.pan}</Badge>}</div></div></CardContent></Card>
  <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-200 p-4"><div><CardTitle className="text-sm">Branches</CardTitle><p className="mt-0.5 text-[10px] text-slate-500">Operational locations under this company</p></div><Badge className="bg-emerald-50 text-emerald-700">{branches.length}</Badge></CardHeader><CardContent className="p-3">{branches.length === 0 ? <div className="p-10 text-center"><Store className="mx-auto size-8 text-slate-300" /><p className="mt-2 text-xs font-bold text-slate-700">No branches created</p><p className="mt-1 text-[10px] text-slate-500">Create your first operational branch.</p></div> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{branches.map(branch => <div key={branch.id} className="rounded-lg border border-slate-200 p-4 transition hover:border-emerald-300 hover:shadow-sm"><div className="flex items-start justify-between"><div><p className="text-[9px] font-bold text-emerald-700">{branch.branch_code}</p><h3 className="mt-1 text-sm font-bold text-slate-950">{branch.name}</h3></div><Badge className={branch.is_active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}>{branch.is_active ? "Active" : "Inactive"}</Badge></div><div className="mt-3 space-y-1.5 text-[10px] text-slate-600"><p className="flex gap-2"><MapPin className="mt-0.5 size-3 shrink-0" />{branch.address_line_1}, {branch.city}, {branch.state} – {branch.postal_code}</p>{branch.manager_name && <p className="flex gap-2"><UserRound className="size-3" />{branch.manager_name}</p>}{branch.mobile_number && <p className="flex gap-2"><Phone className="size-3" />{branch.mobile_number}</p>}</div><div className="mt-4 flex justify-end gap-2"><Button type="button" variant="outline" size="sm" onClick={() => { setEditing(branch); setOpen(true); }}><Pencil className="size-3.5" />Edit</Button><AlertDialog><AlertDialogTrigger render={<Button variant="destructive" size="icon-sm" />}><Trash2 className="size-3.5" /></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {branch.name}?</AlertDialogTitle><AlertDialogDescription>This permanently removes the branch. Existing operational records should be reassigned before deletion.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => remove(branch.id)} className="bg-red-600 text-white">Delete branch</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div>)}</div>}</CardContent></Card></div>;
  async function saveCompany(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!company) return; const data = new FormData(event.currentTarget); const optional = (name: string) => String(data.get(name) ?? "").trim() || null; try { await authenticatedApiRequest("/api/v1/companies/me", { method: "PUT", body: JSON.stringify({ name: data.get("name"), legal_name: optional("legal_name"), mobile_number: data.get("mobile_number"), email: data.get("email"), gstin: optional("gstin"), pan: optional("pan"), website: optional("website"), addresses: [{ address_type: "registered", is_primary: true, address_line_1: data.get("address_line_1"), address_line_2: optional("address_line_2"), locality: optional("locality"), city: data.get("city"), state: data.get("state"), postal_code: data.get("postal_code"), country: "India", landmark: optional("landmark") }] }) }); if (logo) { const form = new FormData(); form.append("logo", logo); const token = localStorage.getItem("zchit_access_token"); const response = await fetch(`${API_URL}/api/v1/companies/me/logo`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); if (!response.ok) throw new Error(await getResponseError(response, "Company details saved, but logo upload failed.")); } setCompanyEditOpen(false); setLogo(null); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update company."); } }
}
function BranchForm({ branch, onSubmit }: { branch: Branch | null; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>{branch ? "Edit branch" : "Create branch"}</SheetTitle></SheetHeader><form onSubmit={onSubmit} className="space-y-4 px-4"><Field label="Branch name" name="name" required defaultValue={branch?.name} /><Field label="Manager name" name="manager_name" defaultValue={branch?.manager_name} /><Field label="Mobile number" name="mobile_number" defaultValue={branch?.mobile_number} /><Field label="Email" name="email" type="email" defaultValue={branch?.email} /><Field label="Address line 1" name="address_line_1" required defaultValue={branch?.address_line_1} /><Field label="Address line 2" name="address_line_2" defaultValue={branch?.address_line_2} /><Field label="Locality" name="locality" defaultValue={branch?.locality} /><Field label="Landmark" name="landmark" defaultValue={branch?.landmark} /><Field label="City" name="city" required defaultValue={branch?.city} /><Field label="State" name="state" required defaultValue={branch?.state} /><Field label="Postal code" name="postal_code" required defaultValue={branch?.postal_code} /><Button type="submit" className="w-full bg-emerald-600 text-white">{branch ? "Save branch" : "Create branch"}</Button></form></SheetContent>; }
function CompanyForm({ company, logo, setLogo, onSubmit }: { company: Company; logo: File | null; setLogo: (file: File | null) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const address = company.addresses[0]; return <SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Edit company profile</SheetTitle></SheetHeader><form onSubmit={onSubmit} className="space-y-4 px-4"><div className="flex items-center gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3">{company.logo_url ? <Image src={company.logo_url} alt="Company logo" width={56} height={56} unoptimized className="size-14 rounded-lg object-contain" /> : <span className="flex size-14 items-center justify-center rounded-lg bg-white text-slate-500"><ImagePlus className="size-5" /></span>}<div className="min-w-0 flex-1"><p className="text-xs font-bold text-slate-800">Company logo</p><p className="truncate text-[10px] text-slate-500">{logo?.name ?? "Keep current logo"}</p></div><label className="cursor-pointer rounded-md border border-slate-300 bg-white px-3 py-2 text-[10px] font-semibold hover:bg-slate-50"><input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={(event) => setLogo(event.target.files?.[0] ?? null)} />Replace</label></div><Field label="Company name" name="name" required defaultValue={company.name} /><Field label="Legal name" name="legal_name" defaultValue={company.legal_name} /><Field label="Mobile number" name="mobile_number" required defaultValue={company.mobile_number} /><Field label="Email" name="email" type="email" required defaultValue={company.email} /><Field label="GSTIN" name="gstin" defaultValue={company.gstin} /><Field label="PAN" name="pan" defaultValue={company.pan} /><Field label="Website" name="website" type="url" defaultValue={company.website} /><Field label="Address line 1" name="address_line_1" required defaultValue={address?.address_line_1} /><Field label="Address line 2" name="address_line_2" defaultValue={address?.address_line_2} /><Field label="Locality" name="locality" defaultValue={address?.locality} /><Field label="Landmark" name="landmark" defaultValue={address?.landmark} /><Field label="City" name="city" required defaultValue={address?.city} /><Field label="State" name="state" required defaultValue={address?.state} /><Field label="Postal code" name="postal_code" required defaultValue={address?.postal_code} /><Button type="submit" className="w-full bg-emerald-600 text-white">Save company profile</Button></form></SheetContent>; }
function Field({ label, name, type = "text", required, defaultValue }: { label: string; name: string; type?: string; required?: boolean; defaultValue?: string | null }) { const[value,setValue]=useState(defaultValue??"");return <div className="space-y-1.5"><Label htmlFor={name} className="text-xs font-semibold">{label}</Label><Input id={name} name={name} type={type} required={required} value={value} onChange={event=>setValue(event.target.value)} className="h-9" /></div>; }
