"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, FileCheck2, Plus, Search, UserRound, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ApiRequestError, authenticatedApiRequest } from "@/lib/api";

type Member = { id: number; member_code: string; full_name: string; mobile_number: string; email: string | null; aadhaar_last4: string; pan: string | null; city: string; state: string; cheque_file_name: string | null; bank_statement_file_name: string | null; references: unknown[]; is_active: boolean };

export default function MembersPage() {
  const [members, setMembers] = useState<Member[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load(search = "") { setLoading(true); try { const data = await authenticatedApiRequest<{ items: Member[]; total: number }>(`/api/v1/members?search=${encodeURIComponent(search)}`); setMembers(data.items); setTotal(data.total); } catch (err) { if (err instanceof ApiRequestError && err.status === 401) window.location.replace("/login"); else setError(err instanceof Error ? err.message : "Unable to load members."); } finally { setLoading(false); } }
  useEffect(() => {
    const timer = window.setTimeout(() => void load(), 0);
    return () => window.clearTimeout(timer);
  }, []);
  return <div className="mx-auto max-w-[1600px] space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Member management</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Members</h1><p className="mt-1 text-[13px] text-slate-600">Manage member identity, KYC documents, addresses, and references.</p></div><Button nativeButton={false} className="h-9 bg-emerald-600 px-3.5 font-semibold text-white hover:bg-emerald-700" render={<Link href="/dashboard/members/new" />}><Plus className="size-4" />Add member</Button></div>
  <div className="grid gap-3 sm:grid-cols-3"><Summary icon={UsersRound} label="Total members" value={String(total)} /><Summary icon={FileCheck2} label="Documents complete" value={String(members.filter(m => m.cheque_file_name && m.bank_statement_file_name).length)} /><Summary icon={UserRound} label="Active members" value={String(members.filter(m => m.is_active).length)} /></div>
  <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="p-0"><div className="flex items-center border-b border-slate-200 p-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><Input placeholder="Search name, mobile, or member code" onChange={(e) => load(e.target.value)} className="h-9 border-slate-300 pl-9" /></div></div>{error && <p className="p-4 text-sm text-red-700">{error}</p>}{loading ? <p className="p-8 text-center text-sm text-slate-500">Loading members…</p> : members.length === 0 ? <div className="p-10 text-center"><UsersRound className="mx-auto size-8 text-slate-400" /><p className="mt-3 text-sm font-bold text-slate-900">No members yet</p><p className="mt-1 text-xs text-slate-500">Add your first member to begin.</p></div> : <div className="overflow-x-auto"><Table className="min-w-[820px] text-xs"><TableHeader><TableRow className="h-9 bg-slate-50"><TableHead className="pl-4">Member</TableHead><TableHead>Contact</TableHead><TableHead>KYC</TableHead><TableHead>Location</TableHead><TableHead>References</TableHead><TableHead>Documents</TableHead><TableHead className="pr-4 text-right">Action</TableHead></TableRow></TableHeader><TableBody>{members.map(member => <TableRow key={member.id} className="h-12"><TableCell className="pl-4"><p className="font-bold text-slate-950">{member.full_name}</p><p className="text-[10px] text-slate-500">{member.member_code}</p></TableCell><TableCell><p>{member.mobile_number}</p><p className="text-[10px] text-slate-500">{member.email ?? "—"}</p></TableCell><TableCell><p>Aadhaar •••• {member.aadhaar_last4}</p><p className="text-[10px] text-slate-500">PAN {member.pan ?? "—"}</p></TableCell><TableCell>{member.city}, {member.state}</TableCell><TableCell>{member.references.length}</TableCell><TableCell><Badge className={member.cheque_file_name && member.bank_statement_file_name ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}>{member.cheque_file_name && member.bank_statement_file_name ? "Complete" : "Pending"}</Badge></TableCell><TableCell className="pr-4 text-right"><Button nativeButton={false} variant="ghost" size="sm" render={<Link href={`/dashboard/members/${member.id}`} />}>View <ArrowRight className="size-3.5" /></Button></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card></div>;
}

function Summary({ icon: Icon, label, value }: { icon: typeof UsersRound; label: string; value: string }) { return <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="flex items-center gap-3 p-4"><span className="flex size-9 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700"><Icon className="size-[18px]" /></span><div><p className="text-[11px] font-semibold text-slate-500">{label}</p><p className="text-xl font-bold text-slate-950">{value}</p></div></CardContent></Card>; }
