"use client";

import Link from "next/link";
import { FormEvent, use, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BadgeIndianRupee, CalendarDays, CheckCircle2, Gavel, LayoutDashboard, Plus, RefreshCw, ReceiptIndianRupee, Scale, UsersRound, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { API_URL, authenticatedApiRequest, getResponseError } from "@/lib/api";

type Schedule = { id: number; installment_number: number; due_date: string; payable_amount: string; receivable_amount: string };
type Member = { enrollment_id: number; member_id: number; member_code: string; full_name: string; mobile_number: string; start_installment: number; end_installment: number | null; status: string; replaced_enrollment_id: number | null; break_reason: string | null };
type AvailableMember = { id: number; member_code: string; full_name: string; mobile_number: string };
type Payment = { id: number; member_id: number; member_name: string; schedule_id: number; installment_number: number; amount: string; received_amount:string; late_fee_amount:string; penalty_amount:string; waiver_amount:string; excess_amount:string; refunded_amount:string; payment_date: string; payment_mode: string; reference_number: string | null; receipt_number: string | null; branch_id: number | null; payment_source: string; status: string };
type Auction = { id: number; schedule_id: number; installment_number: number; due_date: string; winner_member_id: number; winner_name: string; auction_date: string; bid_amount: string; discount_amount: string; commission_amount: string; commission_percent:string; payout_amount: string; settled_installment_amount: string; net_payout_amount: string; status: string; voucher_number: string | null; branch_id: number | null; winner_acknowledged_at:string|null; approved_at:string|null; payout_date:string|null; settlement_proof_file_name:string|null };
type Detail = { id: number; group_code: string; scheme_name: string; scheme_amount: string; start_date: string; duration_months: number; max_member_count:number; active_member_count:number; available_slot_count:number; foreman_commission_percent:string; maturity_date:string|null; grace_period_days:number; late_fee_type:string; late_fee_value:string; status: string; schedules: Schedule[]; members: Member[]; payments: Payment[]; auctions: Auction[] };
type Branch = { id: number; branch_code: string; name: string; is_active: boolean };
type Reconciliation = { expected_total:string; collected_total:string; cash_collected_total:string; auction_settled_total:string; auction_payout_total:string; outstanding_amount:string; pending_auctions:number; expected_closing_balance:string; can_close:boolean };
type Transfer = { id:number; old_member_name:string; replacement_member_name:string; effective_installment:number; effective_date:string; outstanding_balance:string; reason:string; status:string; old_member_consent_file_name:string|null; new_member_consent_file_name:string|null; requested_at:string; approved_at:string|null; approval_notes:string|null };

export default function ChitDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [detail, setDetail] = useState<Detail | null>(null); const [transfers,setTransfers]=useState<Transfer[]>([]); const [availableMembers, setAvailableMembers] = useState<AvailableMember[]>([]); const [branches, setBranches] = useState<Branch[]>([]); const [paymentOpen, setPaymentOpen] = useState(false); const [auctionOpen, setAuctionOpen] = useState(false); const [reconciliationOpen, setReconciliationOpen] = useState(false); const [reconciliation, setReconciliation] = useState<Reconciliation | null>(null); const [replaceEnrollment, setReplaceEnrollment] = useState<Member | null>(null); const [error, setError] = useState("");
  useEffect(() => { const timer = setTimeout(async () => { try { const [group, transferData, memberData, branchData] = await Promise.all([authenticatedApiRequest<Detail>(`/api/v1/chits/${id}`),authenticatedApiRequest<Transfer[]>(`/api/v1/chits/${id}/transfers`), authenticatedApiRequest<{ items: AvailableMember[] }>("/api/v1/members?page_size=100"), authenticatedApiRequest<Branch[]>("/api/v1/branches")]); setDetail(group);setTransfers(transferData); setAvailableMembers(memberData.items); setBranches(branchData.filter(branch => branch.is_active)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load scheme."); } }, 0); return () => clearTimeout(timer); }, [id]);
  async function recordPayment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const amount = Number(data.get("amount")); const lateFeeAmount = Number(data.get("late_fee_amount") || 0); const penaltyAmount = Number(data.get("penalty_amount") || 0); const waiverAmount = Number(data.get("waiver_amount") || 0); const excessAmount = Number(data.get("excess_amount") || 0); const receivedAmount = amount + lateFeeAmount + penaltyAmount - waiverAmount + excessAmount; try { setDetail(await authenticatedApiRequest<Detail>(`/api/v1/chits/${id}/payments`, { method: "POST", body: JSON.stringify({ member_id: Number(data.get("member_id")), schedule_id: Number(data.get("schedule_id")), amount, received_amount: receivedAmount, late_fee_amount: lateFeeAmount, penalty_amount: penaltyAmount, waiver_amount: waiverAmount, waiver_reason: data.get("waiver_reason") || null, excess_amount: excessAmount, collection_location_text: data.get("collection_location_text") || null, payment_date: data.get("payment_date"), payment_mode: data.get("payment_mode"), reference_number: data.get("reference_number") || null, notes: data.get("notes") || null, branch_id: data.get("branch_id") ? Number(data.get("branch_id")) : null, payment_source: data.get("payment_source") || "manual" }) })); setPaymentOpen(false); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to record payment."); } }
  async function recordAuction(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { setDetail(await authenticatedApiRequest<Detail>(`/api/v1/chits/${id}/auctions`, { method: "POST", body: JSON.stringify({ schedule_id: Number(data.get("schedule_id")), winner_member_id: Number(data.get("winner_member_id")), auction_date: data.get("auction_date"), bid_amount: Number(data.get("bid_amount")), discount_amount: Number(data.get("discount_amount")), notes: data.get("notes") || null, branch_id: data.get("branch_id") ? Number(data.get("branch_id")) : null }) })); setAuctionOpen(false); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create auction."); } }
  async function replaceMember(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!replaceEnrollment) return; const data = new FormData(event.currentTarget); data.set("old_member_acknowledged","true");data.set("new_member_acknowledged","true"); try { const token=localStorage.getItem("zchit_access_token");const response=await fetch(`${API_URL}/api/v1/chits/${id}/enrollments/${replaceEnrollment.enrollment_id}/replace`,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:data});if(!response.ok)throw new Error(await getResponseError(response,"Unable to request replacement."));setTransfers(await authenticatedApiRequest<Transfer[]>(`/api/v1/chits/${id}/transfers`)); setReplaceEnrollment(null); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to request replacement."); } }
  async function approveTransfer(transferId:number){try{setDetail(await authenticatedApiRequest<Detail>(`/api/v1/chits/${id}/transfers/${transferId}/approve`,{method:"POST",body:JSON.stringify({approval_notes:"Consent documents verified"})}));setTransfers(await authenticatedApiRequest<Transfer[]>(`/api/v1/chits/${id}/transfers`));setError("");}catch(err){setError(err instanceof Error?err.message:"Unable to approve replacement.");}}
  async function openReconciliation() { try { setReconciliation(await authenticatedApiRequest<Reconciliation>(`/api/v1/chits/${id}/reconciliation`)); setReconciliationOpen(true); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to reconcile scheme."); } }
  async function closeScheme(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data=new FormData(event.currentTarget); try { await authenticatedApiRequest(`/api/v1/chits/${id}/close`, {method:"POST",body:JSON.stringify({actual_closing_balance:Number(data.get("actual_closing_balance")),variance_reason:data.get("variance_reason")||null})}); setDetail(await authenticatedApiRequest<Detail>(`/api/v1/chits/${id}`)); setReconciliationOpen(false); setError(""); } catch(err) { setError(err instanceof Error?err.message:"Unable to close scheme."); } }
  async function cancelScheme(){const reason=window.prompt("Scheme cancellation reason");if(!reason)return;try{setDetail(await authenticatedApiRequest<Detail>(`/api/v1/chits/${id}/cancel`,{method:"POST",body:JSON.stringify({reason})}));setError("");}catch(err){setError(err instanceof Error?err.message:"Unable to cancel scheme.");}}
  if (error && !detail) return <p className="rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p>; if (!detail) return <p className="p-8 text-center text-sm text-slate-500">Loading scheme…</p>;
  const collected = detail.payments.reduce((sum, payment) => sum + Number(payment.amount), 0);
  return <div className="mx-auto max-w-[1600px] space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Button nativeButton={false} variant="outline" size="icon" render={<Link href="/dashboard/chits" />}><ArrowLeft className="size-4" /></Button><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-700">{detail.group_code}</p><h1 className="mt-0.5 text-xl font-bold text-slate-950">{detail.scheme_name}</h1></div></div><div className="flex gap-2">{["draft","active"].includes(detail.status)&&<Button type="button" variant="destructive" className="h-9" onClick={()=>void cancelScheme()}>Cancel scheme</Button>}{detail.status === "active" && <><Button type="button" variant="outline" className="h-9" onClick={() => void openReconciliation()}><Scale className="size-4"/>Final reconciliation</Button><AuctionSheet detail={detail} branches={branches} open={auctionOpen} setOpen={setAuctionOpen} onSubmit={recordAuction} /><PaymentSheet detail={detail} branches={branches} open={paymentOpen} setOpen={setPaymentOpen} onSubmit={recordPayment} /></>}</div></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary icon={WalletCards} label="Scheme value" value={`₹${Number(detail.scheme_amount).toLocaleString("en-IN")}`} /><Summary icon={CalendarDays} label="Status" value={detail.status.toUpperCase()} /><Summary icon={UsersRound} label="Members / slots" value={`${detail.active_member_count} / ${detail.max_member_count}`} /><Summary icon={BadgeIndianRupee} label="Foreman commission" value={`${detail.foreman_commission_percent}%`} /><Summary icon={BadgeIndianRupee} label="Cash collected" value={`₹${collected.toLocaleString("en-IN")}`} /></div>{error && <p className="rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}
  <Tabs defaultValue="overview" className="gap-4"><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white p-1 shadow-sm"><TabsList className="h-10 min-w-max bg-transparent p-0"><TabsTrigger value="overview" className="h-9 gap-2 px-4 text-xs font-semibold data-active:bg-emerald-600 data-active:text-white"><LayoutDashboard className="size-3.5" />Overview</TabsTrigger><TabsTrigger value="schedule" className="h-9 gap-2 px-4 text-xs font-semibold data-active:bg-emerald-600 data-active:text-white"><CalendarDays className="size-3.5" />Schedule</TabsTrigger><TabsTrigger value="members" className="h-9 gap-2 px-4 text-xs font-semibold data-active:bg-emerald-600 data-active:text-white"><UsersRound className="size-3.5" />Members</TabsTrigger><TabsTrigger value="auctions" className="h-9 gap-2 px-4 text-xs font-semibold data-active:bg-emerald-600 data-active:text-white"><Gavel className="size-3.5" />Auctions</TabsTrigger><TabsTrigger value="collections" className="h-9 gap-2 px-4 text-xs font-semibold data-active:bg-emerald-600 data-active:text-white"><ReceiptIndianRupee className="size-3.5" />Collections</TabsTrigger></TabsList></div>
  <TabsContent value="overview" className="mt-0"><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><ScheduleTable rows={detail.schedules} /><MemberList members={detail.members} groupId={id} onReplace={setReplaceEnrollment} /></div></TabsContent>
  <TabsContent value="schedule" className="mt-0"><ScheduleTable rows={detail.schedules} /></TabsContent>
  <TabsContent value="members" className="mt-0"><div className="space-y-4"><MemberList members={detail.members} groupId={id} onReplace={setReplaceEnrollment} /><TransferList transfers={transfers} onApprove={approveTransfer}/></div></TabsContent>
  <TabsContent value="auctions" className="mt-0"><AuctionList auctions={detail.auctions} /></TabsContent>
  <TabsContent value="collections" className="mt-0"><PaymentList payments={detail.payments} /></TabsContent></Tabs><ReplaceSheet enrollment={replaceEnrollment} setEnrollment={setReplaceEnrollment} availableMembers={availableMembers.filter(member => !detail.members.some(item => item.member_id === member.id && item.status === "active"))} duration={detail.duration_months} onSubmit={replaceMember} /><ReconciliationSheet open={reconciliationOpen} setOpen={setReconciliationOpen} data={reconciliation} onSubmit={closeScheme}/></div>;
}
function ReconciliationSheet({open,setOpen,data,onSubmit}:{open:boolean;setOpen:(value:boolean)=>void;data:Reconciliation|null;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}) { return <Sheet open={open} onOpenChange={setOpen}><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Final scheme reconciliation</SheetTitle></SheetHeader>{data&&<form onSubmit={onSubmit} className="space-y-4 px-4"><div className="grid grid-cols-2 gap-2">{[["Expected dues",data.expected_total],["Principal collected",data.collected_total],["Cash collected",data.cash_collected_total],["Auction settlements",data.auction_settled_total],["Cash payouts",data.auction_payout_total],["Outstanding",data.outstanding_amount],["Expected closing balance",data.expected_closing_balance]].map(([label,value])=><div key={label} className="rounded-lg border border-slate-200 p-3"><p className="text-[10px] font-semibold text-slate-600">{label}</p><p className="mt-1 text-sm font-bold text-slate-950">₹{Number(value).toLocaleString("en-IN")}</p></div>)}</div><div className={`rounded-lg border p-3 ${data.can_close?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><p className="text-xs font-bold text-slate-950">{data.can_close?"Ready to close":"Reconciliation incomplete"}</p><p className="mt-1 text-[11px] text-slate-700">{data.pending_auctions} pending auctions · ₹{Number(data.outstanding_amount).toLocaleString("en-IN")} outstanding</p></div><Field label="Actual closing balance" name="actual_closing_balance" type="number" required/><Field label="Variance reason (required when balance differs)" name="variance_reason"/><Button type="submit" disabled={!data.can_close} className="w-full bg-emerald-600 text-white"><CheckCircle2 className="size-4"/>Close scheme permanently</Button></form>}</SheetContent></Sheet>; }
function AuctionSheet({ detail, branches, open, setOpen, onSubmit }: { detail: Detail; branches: Branch[]; open: boolean; setOpen: (v: boolean) => void; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { const activeAuctions = detail.auctions.filter(item => !["cancelled", "reversed"].includes(item.status)); const auctionedSchedules = new Set(activeAuctions.map(item => item.schedule_id)); const auctionedWinners = new Set(activeAuctions.map(item => item.winner_member_id)); return <Sheet open={open} onOpenChange={setOpen}><SheetTrigger render={<Button variant="outline" className="h-9" />}><Gavel className="size-4" />Create auction</SheetTrigger><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Create scheme auction</SheetTitle></SheetHeader><form onSubmit={onSubmit} className="space-y-4 px-4"><HumanSelect name="schedule_id" placeholder="Choose installment" items={detail.schedules.filter(row => !auctionedSchedules.has(row.id) && Number(row.receivable_amount) > 0).map(row => ({ value: String(row.id), label: `Installment #${row.installment_number} · ${new Date(row.due_date).toLocaleDateString("en-IN")} · Receivable ₹${Number(row.receivable_amount).toLocaleString("en-IN")}` }))} /><HumanSelect name="winner_member_id" placeholder="Choose auction winner" items={detail.members.filter(member => member.status === "active" && !auctionedWinners.has(member.member_id)).map(member => ({ value: String(member.member_id), label: `${member.full_name} · ${member.member_code}` }))} />{branches.length > 0 && <HumanSelect name="branch_id" placeholder="Choose branch" items={branches.map(branch => ({ value: String(branch.id), label: `${branch.name} · ${branch.branch_code}` }))} />}<Field label="Auction date" name="auction_date" type="date" required /><Field label="Bid amount" name="bid_amount" type="number" required /><Field label="Discount amount" name="discount_amount" type="number" required /><Field label="Notes" name="notes" /><p className="rounded-lg bg-emerald-50 p-3 text-[11px] text-emerald-900">Foreman commission comes automatically from this scheme&apos;s configured rate. This creates a pending auction; approval must happen before payout, and payout is recorded separately afterward.</p><Button type="submit" className="w-full bg-emerald-600 text-white">Create pending auction</Button></form></SheetContent></Sheet>; }
function PaymentSheet({ detail, branches, open, setOpen, onSubmit }: { detail: Detail; branches: Branch[]; open: boolean; setOpen: (v: boolean) => void; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) {
  const [memberId, setMemberId] = useState<string | null>(null);
  const [scheduleId, setScheduleId] = useState<string | null>(null);
  const member = detail.members.find(item => String(item.member_id) === memberId);
  const installmentRows = member ? detail.schedules
    .filter(row => row.installment_number >= member.start_installment && (member.end_installment === null || row.installment_number <= member.end_installment))
    .map(row => {
      const paid = detail.payments.filter(payment => payment.member_id === member.member_id && payment.schedule_id === row.id && payment.status === "posted").reduce((sum, payment) => sum + Number(payment.amount), 0);
      const auction = detail.auctions.find(item => item.winner_member_id === member.member_id && item.schedule_id === row.id && !["cancelled", "reversed"].includes(item.status));
      const balance = Math.max(0, Number(row.payable_amount) - paid - Number(auction?.settled_installment_amount ?? 0));
      return { ...row, paid, balance, disabled: Boolean(auction) || balance <= 0, status: auction ? "Auction settled" : balance <= 0 ? "Paid" : paid > 0 ? "Partial" : "Unpaid" };
    }) : [];
  const selectedRow = installmentRows.find(row => String(row.id) === scheduleId);
  function changeOpen(value: boolean) { setOpen(value); if (!value) { setMemberId(null); setScheduleId(null); } }
  function changeMember(value: string | null) { setMemberId(value); setScheduleId(null); }
  return <Sheet open={open} onOpenChange={changeOpen}><SheetTrigger render={<Button className="h-9 bg-emerald-600 text-white" />}><Plus className="size-4" />Record payment</SheetTrigger><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Record collection</SheetTitle></SheetHeader><form onSubmit={onSubmit} className="space-y-4 px-4">
    <Select name="member_id" value={memberId} onValueChange={changeMember} required><SelectTrigger className="w-full"><SelectValue>{member ? `${member.full_name} · ${member.member_code}` : "Choose member"}</SelectValue></SelectTrigger><SelectContent>{detail.members.filter(item => item.status === "active").map(item => <SelectItem key={item.member_id} value={String(item.member_id)}>{item.full_name} · {item.member_code}</SelectItem>)}</SelectContent></Select>
    {!member ? <div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs font-semibold text-slate-700">Select a member to view installment payment status.</div> : <div className="space-y-2"><Label className="text-xs font-semibold text-slate-700">Installment</Label><Select name="schedule_id" value={scheduleId} onValueChange={setScheduleId} required><SelectTrigger className="w-full"><SelectValue>{selectedRow ? `Installment #${selectedRow.installment_number} · Balance ₹${selectedRow.balance.toLocaleString("en-IN")}` : "Choose an unpaid installment"}</SelectValue></SelectTrigger><SelectContent>{installmentRows.map(row => <SelectItem key={row.id} value={String(row.id)} disabled={row.disabled}>#{row.installment_number} · {new Date(row.due_date).toLocaleDateString("en-IN")} · Payable ₹{Number(row.payable_amount).toLocaleString("en-IN")} · Paid ₹{row.paid.toLocaleString("en-IN")} · Balance ₹{row.balance.toLocaleString("en-IN")} · {row.status}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-3 gap-2">{[["Payable", selectedRow ? Number(selectedRow.payable_amount) : 0], ["Paid", selectedRow?.paid ?? 0], ["Balance", selectedRow?.balance ?? 0]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-slate-200 bg-white p-2.5"><p className="text-[10px] font-semibold text-slate-700">{label}</p><p className="mt-1 text-xs font-bold text-slate-950">₹{Number(value).toLocaleString("en-IN")}</p></div>)}</div><p className="text-[11px] text-slate-700">Paid and auction-settled installments are disabled. Unpaid and partial past, current, and future installments remain available.</p></div>}
    {branches.length > 0 && <HumanSelect name="branch_id" placeholder="Choose branch" items={branches.map(branch => ({ value: String(branch.id), label: `${branch.name} · ${branch.branch_code}` }))} />}<Field label="Principal amount (partial or full)" name="amount" type="number" required /><Field label="Late fee amount" name="late_fee_amount" type="number" /><Field label="Penalty amount" name="penalty_amount" type="number" /><Field label="Waiver amount" name="waiver_amount" type="number" /><Field label="Waiver reason" name="waiver_reason" /><Field label="Excess amount" name="excess_amount" type="number" /><Field label="Collection location" name="collection_location_text" /><Field label="Payment date" name="payment_date" type="date" required /><HumanSelect name="payment_mode" placeholder="Payment mode" items={["cash", "upi", "bank", "cheque"].map(mode => ({ value: mode, label: mode.toUpperCase() }))} /><HumanSelect name="payment_source" placeholder="Payment source" items={[{ value: "manual", label: "Office manual entry" }, { value: "agent", label: "Collection agent" }, { value: "online", label: "Online payment" }, { value: "bank_import", label: "Bank import" }]} /><Field label="Reference number" name="reference_number" /><Field label="Notes" name="notes" /><p className="rounded-lg bg-blue-50 p-3 text-[11px] text-blue-900">Received amount is calculated as principal + late fee + penalty − waiver + excess. Partial payments are allowed, and receipt and ledger entries are generated automatically.</p><Button type="submit" disabled={!member || !selectedRow} className="w-full bg-emerald-600 text-white">Save payment & receipt</Button>
  </form></SheetContent></Sheet>;
}
function HumanSelect({ name, placeholder, items }: { name: string; placeholder: string; items: { value: string; label: string }[] }) { const [value, setValue] = useState<string | null>(null); const selectedLabel = items.find(item => item.value === value)?.label; return <Select name={name} value={value} onValueChange={setValue} required><SelectTrigger className="w-full"><SelectValue>{selectedLabel ?? placeholder}</SelectValue></SelectTrigger><SelectContent>{items.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select>; }
function ReplaceSheet({ enrollment, setEnrollment, availableMembers, duration, onSubmit }: { enrollment: Member | null; setEnrollment: (member: Member | null) => void; availableMembers: AvailableMember[]; duration: number; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <Sheet open={Boolean(enrollment)} onOpenChange={(open) => !open && setEnrollment(null)}><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Request member replacement</SheetTitle></SheetHeader>{enrollment && <form onSubmit={onSubmit} encType="multipart/form-data" className="space-y-4 px-4"><div className="rounded-lg border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-bold text-slate-950">{enrollment.full_name}</p><p className="mt-1 text-[10px] text-slate-600">Historical payments and auctions remain with this member. Transfer activates only after approval.</p></div><HumanSelect name="replacement_member_id" placeholder="Choose replacement member" items={availableMembers.map(member => ({ value: String(member.id), label: `${member.full_name} · ${member.member_code} · ${member.mobile_number}` }))} /><Field label="Effective from installment" name="effective_installment" type="number" required /><Field label="Transfer effective date" name="effective_date" type="date" required /><Field label="Reason" name="reason" required/><ConsentUpload name="old_member_consent" label="Existing member consent"/><ConsentUpload name="new_member_consent" label="Replacement member consent"/><div className="rounded-lg bg-emerald-50 p-3 text-[11px] text-emerald-900">Submitting confirms both members acknowledged the transfer. Outstanding balance is snapshotted and must be cleared before owner approval. Replacement runs from the selected installment through {duration}.</div><Button type="submit" className="w-full bg-emerald-600 text-white">Submit replacement request</Button></form>}</SheetContent></Sheet>; }
function ConsentUpload({name,label}:{name:string;label:string}){return <div className="space-y-1.5"><Label htmlFor={name} className="text-xs font-semibold text-slate-700">{label} *</Label><Input id={name} name={name} type="file" accept="application/pdf,image/jpeg,image/png" required className="h-9"/></div>;}
function TransferList({transfers,onApprove}:{transfers:Transfer[];onApprove:(id:number)=>void}){return <Card className="border border-slate-200 bg-white py-0 ring-0"><SectionHeader icon={RefreshCw} title="Replacement history" subtitle="Consent, outstanding snapshot, approval, and transfer audit" count={transfers.length}/><CardContent className="space-y-2 p-3">{transfers.length===0?<p className="p-6 text-center text-xs text-slate-500">No replacement requests.</p>:transfers.map(item=><div key={item.id} className="grid gap-3 rounded-lg border border-slate-200 p-3 md:grid-cols-[1fr_1fr_1fr_1fr_auto]"><div><p className="text-[9px] font-bold text-slate-500">FROM → TO</p><p className="text-xs font-bold text-slate-950">{item.old_member_name} → {item.replacement_member_name}</p></div><div><p className="text-[9px] font-bold text-slate-500">EFFECTIVE</p><p className="text-xs font-semibold">Installment {item.effective_installment} · {new Date(`${item.effective_date}T00:00:00`).toLocaleDateString("en-IN")}</p></div><div><p className="text-[9px] font-bold text-slate-500">OUTSTANDING SNAPSHOT</p><p className="text-xs font-bold text-red-700">₹{Number(item.outstanding_balance).toLocaleString("en-IN")}</p></div><div><p className="text-[9px] font-bold text-slate-500">STATUS</p><p className="text-xs font-bold text-emerald-700">{item.status.toUpperCase()}</p><p className="text-[9px] text-slate-500">{item.reason}</p></div>{item.status==="pending"?<Button type="button" size="sm" disabled={Number(item.outstanding_balance)>0} onClick={()=>onApprove(item.id)} className="bg-emerald-600 text-white">Approve</Button>:<span className="text-xs font-semibold text-slate-600">Approved</span>}</div>)}</CardContent></Card>;}
function SectionHeader({ icon: Icon, title, subtitle, count }: { icon: typeof CalendarDays; title: string; subtitle: string; count: number }) { return <CardHeader className="flex flex-row items-center justify-between border-b border-slate-200 bg-gradient-to-r from-slate-50 to-white p-4"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-emerald-100 text-emerald-700"><Icon className="size-[18px]" /></span><div><CardTitle className="text-sm font-bold text-slate-950">{title}</CardTitle><p className="mt-0.5 text-[10px] text-slate-500">{subtitle}</p></div></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">{count}</span></CardHeader>; }
function ScheduleTable({ rows }: { rows: Schedule[] }) { return <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><SectionHeader icon={CalendarDays} title="Full installment schedule" subtitle="Member payable and auction receivable amounts" count={rows.length} /><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[560px] text-xs"><thead className="border-b border-slate-200 bg-slate-50 text-slate-700"><tr><th className="px-4 py-3 text-left text-[10px] font-bold">Installment</th><th className="px-4 py-3 text-left text-[10px] font-bold">Date</th><th className="px-4 py-3 text-right text-[10px] font-bold">Payable amount</th><th className="px-4 py-3 text-right text-[10px] font-bold">Receivable amount</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id} className={`border-b border-slate-100 transition hover:bg-emerald-50 ${index % 2 ? "bg-slate-50/70" : "bg-white"}`}><td className="px-4 py-3"><span className="inline-flex size-7 items-center justify-center rounded-md bg-slate-100 text-[11px] font-bold text-slate-700">{row.installment_number}</span></td><td className="px-4 py-3 font-semibold text-slate-700">{new Date(row.due_date).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}</td><td className="px-4 py-3 text-right"><span className="rounded-md bg-blue-50 px-2 py-1 font-bold text-blue-700">₹{Number(row.payable_amount).toLocaleString("en-IN")}</span></td><td className="px-4 py-3 text-right"><span className="rounded-md bg-emerald-50 px-2 py-1 font-bold text-emerald-700">₹{Number(row.receivable_amount).toLocaleString("en-IN")}</span></td></tr>)}</tbody></table></CardContent></Card>; }
function MemberList({ members, groupId, onReplace }: { members: Member[]; groupId: string; onReplace: (member: Member) => void }) { return <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><SectionHeader icon={UsersRound} title="Enrolled members" subtitle="Open a member to view the full ledger" count={members.length} /><CardContent className="grid gap-2 p-3 sm:grid-cols-2 lg:grid-cols-1">{members.map(member => <div key={member.enrollment_id} className={`group flex items-center gap-3 rounded-lg border p-3 transition ${member.status === "active" ? "border-slate-200 bg-white hover:border-emerald-300 hover:bg-emerald-50" : "border-amber-200 bg-amber-50/50"}`}><Link href={`/dashboard/chits/${groupId}/members/${member.member_id}`} className="flex min-w-0 flex-1 items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-800 ring-2 ring-white">{member.full_name[0]}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-xs font-bold text-slate-950">{member.full_name}</p><span className={`rounded px-1.5 py-0.5 text-[8px] font-bold uppercase ${member.status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{member.status}</span></div><p className="mt-0.5 truncate text-[10px] text-slate-500">{member.member_code} · Installments {member.start_installment}–{member.end_installment ?? "end"}</p></div></Link>{member.status === "active" ? <Button type="button" variant="ghost" size="icon-sm" onClick={() => onReplace(member)} aria-label={`Replace ${member.full_name}`}><RefreshCw className="size-3.5" /></Button> : <ArrowRight className="size-3.5 text-slate-400" />}</div>)}</CardContent></Card>; }
function AuctionList({ auctions }: { auctions: Auction[] }) { return <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><SectionHeader icon={Gavel} title="Auction settlements" subtitle="Winner payout and installment adjustments" count={auctions.length} /><CardContent className="p-3">{auctions.length === 0 ? <div className="p-10 text-center"><Gavel className="mx-auto size-8 text-slate-300" /><p className="mt-2 text-xs font-bold text-slate-700">No auctions recorded</p></div> : <div className="space-y-2">{auctions.map(item => <div key={item.id} className={`grid gap-3 rounded-lg border p-4 transition sm:grid-cols-[.7fr_1fr_1fr_1fr_auto] ${item.status === "reversed" ? "border-red-200 bg-red-50/40" : "border-slate-200 bg-gradient-to-r from-white to-emerald-50/40 hover:border-emerald-300"}`}><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Installment</p><p className="mt-1 text-xs font-bold text-slate-950">#{item.installment_number}</p></div><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Winner</p><p className="mt-1 text-xs font-bold text-slate-950">{item.winner_name}</p></div><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Gross payout</p><p className="mt-1 text-xs font-bold text-slate-950">₹{Number(item.payout_amount).toLocaleString("en-IN")}</p></div><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Net payout</p><p className="mt-1 text-sm font-bold text-emerald-700">₹{Number(item.net_payout_amount).toLocaleString("en-IN")}</p></div><Button nativeButton={false} variant="outline" size="sm" render={<Link href={`/dashboard/vouchers/auctions/${item.id}`} />}>Voucher</Button></div>)}</div>}</CardContent></Card>; }
function PaymentList({ payments }: { payments: Payment[] }) { return <Card className="overflow-hidden border border-slate-200 bg-white py-0 shadow-sm ring-0"><SectionHeader icon={ReceiptIndianRupee} title="Collection history" subtitle="Recorded member installment payments" count={payments.length} /><CardContent className="p-3">{payments.length === 0 ? <div className="p-10 text-center"><ReceiptIndianRupee className="mx-auto size-8 text-slate-300" /><p className="mt-2 text-xs font-bold text-slate-700">No payments recorded</p></div> : <div className="space-y-2">{payments.slice().reverse().map(item => <div key={item.id} className={`flex items-center gap-3 rounded-lg border p-3 transition ${item.status === "reversed" ? "border-red-200 bg-red-50/40" : "border-slate-200 bg-white hover:border-emerald-300 hover:bg-emerald-50"}`}><span className="flex size-9 items-center justify-center rounded-lg bg-emerald-100 text-emerald-700"><BadgeIndianRupee className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-slate-950">{item.member_name}</p><p className="mt-0.5 text-[10px] text-slate-500">{item.receipt_number ?? "Legacy payment"} · Installment #{item.installment_number} · {item.payment_mode.toUpperCase()}</p></div><p className="rounded-md bg-emerald-50 px-2.5 py-1.5 text-xs font-bold text-emerald-700">₹{Number(item.amount).toLocaleString("en-IN")}</p><Button nativeButton={false} variant="outline" size="sm" render={<Link href={`/dashboard/receipts/${item.id}`} />}>Receipt</Button></div>)}</div>}</CardContent></Card>; }
function Summary({ icon: Icon, label, value }: { icon: typeof WalletCards; label: string; value: string }) { return <Card className="border border-slate-200 bg-white py-0 ring-0"><CardContent className="flex items-center gap-3 p-4"><Icon className="size-5 text-emerald-700" /><div><p className="text-[10px] text-slate-500">{label}</p><p className="text-sm font-bold">{value}</p></div></CardContent></Card>; }
function Field({ label, name, type = "text", required }: { label: string; name: string; type?: string; required?: boolean }) { return <div className="space-y-1.5"><Label htmlFor={name} className="text-xs">{label}</Label><Input id={name} name={name} type={type} required={required} className="h-9" /></div>; }
