"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";
import { ArrowLeft, BadgeIndianRupee, Banknote, Download, FileCheck2, FileText, Gavel, Mail, MapPin, Pencil, Phone, ShieldCheck, Trash2, UserRound, UsersRound } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { API_URL, ApiRequestError, authenticatedApiRequest, getResponseError } from "@/lib/api";

type Reference = { id: number; name: string; mobile_number: string; relationship: string | null };
type Member = {
  id: number; member_code: string; full_name: string; date_of_birth: string | null; mobile_number: string; email: string | null;
  aadhaar_last4: string; pan: string | null; address_line_1: string; address_line_2: string | null;
  nominee_name: string | null; nominee_relationship: string | null; nominee_mobile_number: string | null; nominee_date_of_birth: string | null;
  bank_account_holder_name: string | null; bank_account_number: string | null; bank_name: string | null; bank_branch_name: string | null; bank_ifsc_code: string | null; bank_account_type: string | null;
  gender: string | null; kyc_status: string; aadhaar_verification_status: string; pan_verification_status: string;
  kyc_rejection_reason: string | null; kyc_notes: string | null; internal_notes: string | null; risk_flags: string[];
  archived_at: string | null; archive_reason: string | null;
  locality: string | null; city: string; state: string; postal_code: string; country: string; landmark: string | null;
  photo_file_name: string | null; aadhaar_document_file_name: string | null; pan_document_file_name: string | null;
  cheque_file_name: string | null; bank_statement_file_name: string | null; is_active: boolean;
  references: Reference[]; created_at: string;
};
type FinancialSummary = { total_collected: string; payment_count: number; auction_settlement_count: number; gross_payout: string; net_payout: string };

export default function MemberDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [member, setMember] = useState<Member | null>(null); const [summary, setSummary] = useState<FinancialSummary | null>(null); const [photoUrl, setPhotoUrl] = useState<string | undefined>(); const [error, setError] = useState(""); const [deleting, setDeleting] = useState(false);
  useEffect(() => { const timer = window.setTimeout(async () => { try { const [data, financial] = await Promise.all([authenticatedApiRequest<Member>(`/api/v1/members/${id}`), authenticatedApiRequest<FinancialSummary>(`/api/v1/members/${id}/financial-summary`)]); setMember(data); setSummary(financial); if (data.photo_file_name) setPhotoUrl(await fetchPrivateFile(id, "photo")); } catch (err) { if (err instanceof ApiRequestError && err.status === 401) window.location.replace("/login"); else setError(err instanceof Error ? err.message : "Unable to load member."); } }, 0); return () => window.clearTimeout(timer); }, [id]);
  useEffect(() => () => { if (photoUrl) URL.revokeObjectURL(photoUrl); }, [photoUrl]);
  if (error) return <div className="mx-auto max-w-5xl rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>;
  if (!member) return <p className="p-8 text-center text-sm text-slate-500">Loading member…</p>;
  async function deleteMember() { setDeleting(true); try { await authenticatedApiRequest(`/api/v1/members/${id}`, { method: "DELETE" }); setMember(await authenticatedApiRequest<Member>(`/api/v1/members/${id}`)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to archive member."); } finally { setDeleting(false); } }
  async function restoreMember() { try { setMember(await authenticatedApiRequest<Member>(`/api/v1/members/${id}/restore`, { method: "POST" })); } catch (err) { setError(err instanceof Error ? err.message : "Unable to restore member."); } }
  async function reviewKyc(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { setMember(await authenticatedApiRequest<Member>(`/api/v1/members/${id}/kyc`, { method: "PUT", body: JSON.stringify({ aadhaar_status: data.get("aadhaar_status"), pan_status: data.get("pan_status"), notes: data.get("notes") || null, rejection_reason: data.get("rejection_reason") || null }) })); } catch (err) { setError(err instanceof Error ? err.message : "Unable to review KYC."); } }
  const initials = member.full_name.split(" ").map(part => part[0]).slice(0, 2).join("").toUpperCase();
  return <div className="mx-auto max-w-5xl space-y-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Button nativeButton={false} variant="outline" size="icon" render={<Link href="/dashboard/members" />}><ArrowLeft className="size-4" /></Button><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-700">Member profile</p><h1 className="mt-0.5 text-xl font-bold text-slate-950">{member.full_name}</h1></div></div><div className="flex flex-wrap items-center gap-2"><Badge className={member.is_active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-700"}>{member.is_active ? "Active" : "Archived"}</Badge><Badge className={member.kyc_status === "verified" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}>KYC {member.kyc_status}</Badge><KycSheet onSubmit={reviewKyc} /><Button nativeButton={false} variant="outline" className="h-8" render={<Link href={`/dashboard/ledger?member_id=${id}`} />}>Ledger</Button><Button nativeButton={false} variant="outline" className="h-8" render={<Link href={`/dashboard/members/${id}/edit`} />}><Pencil className="size-3.5" />Edit</Button>{member.is_active ? <AlertDialog><AlertDialogTrigger render={<Button variant="destructive" className="h-8" />}><Trash2 className="size-3.5" />Archive</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Archive this member?</AlertDialogTitle><AlertDialogDescription>Financial history and private documents remain preserved. Archived members cannot enter new schemes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={deleting} onClick={deleteMember} className="bg-red-600 text-white hover:bg-red-700">{deleting ? "Archiving…" : "Archive member"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> : <Button type="button" onClick={() => void restoreMember()} className="h-8 bg-emerald-600 text-white">Restore</Button>}</div></div>
    <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><Avatar className="size-20 rounded-xl"><AvatarImage src={photoUrl} className="object-cover" /><AvatarFallback className="rounded-xl bg-emerald-100 text-lg font-bold text-emerald-800">{initials}</AvatarFallback></Avatar><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold text-slate-950">{member.full_name}</h2><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{member.member_code}</span></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-600"><span className="flex items-center gap-1.5"><Phone className="size-3.5" />{member.mobile_number}</span><span className="flex items-center gap-1.5"><Mail className="size-3.5" />{member.email ?? "No email"}</span><span className="flex items-center gap-1.5"><MapPin className="size-3.5" />{member.city}, {member.state}</span></div></div><p className="text-[10px] font-medium text-slate-500">Joined {new Date(member.created_at).toLocaleDateString("en-IN")}</p></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-[1fr_.85fr]">
      <div className="space-y-4"><Section icon={ShieldCheck} title="KYC information"><Info label="Date of birth" value={formatDate(member.date_of_birth)} /><Info label="Aadhaar" value={`•••• •••• ${member.aadhaar_last4}`} /><Info label="PAN" value={member.pan ?? "Not provided"} /></Section><Section icon={UsersRound} title="Nominee details"><Info label="Name" value={member.nominee_name ?? "Not provided"} /><Info label="Relationship" value={member.nominee_relationship ?? "Not provided"} /><Info label="Mobile number" value={member.nominee_mobile_number ?? "Not provided"} /><Info label="Date of birth" value={formatDate(member.nominee_date_of_birth)} /></Section><Section icon={MapPin} title="Residential address"><p className="text-xs leading-6 text-slate-700">{member.address_line_1}{member.address_line_2 && <>, {member.address_line_2}</>}{member.locality && <>, {member.locality}</>}<br />{member.city}, {member.state} – {member.postal_code}<br />{member.country}{member.landmark && <> · Near {member.landmark}</>}</p></Section><Section icon={UsersRound} title={`References (${member.references.length})`}>{member.references.length === 0 ? <p className="text-xs text-slate-500">No references added.</p> : <div className="space-y-2">{member.references.map(reference => <div key={reference.id} className="flex items-center gap-3 rounded-lg border border-slate-200 p-3"><span className="flex size-8 items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-slate-700">{reference.name[0]}</span><div className="flex-1"><p className="text-xs font-bold text-slate-950">{reference.name}</p><p className="mt-0.5 text-[10px] text-slate-500">{reference.mobile_number}{reference.relationship && ` · ${reference.relationship}`}</p></div></div>)}</div>}</Section></div>
      <div className="space-y-4">{summary && <Section icon={BadgeIndianRupee} title="Financial activity"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1"><FinancialCard icon={BadgeIndianRupee} label="Payment collections" value={`₹${Number(summary.total_collected).toLocaleString("en-IN")}`} note={`${summary.payment_count} recorded payments`} tone="emerald" /><FinancialCard icon={Gavel} label="Auction settlements" value={String(summary.auction_settlement_count)} note={`Gross ₹${Number(summary.gross_payout).toLocaleString("en-IN")} · Net ₹${Number(summary.net_payout).toLocaleString("en-IN")}`} tone="violet" /></div></Section>}<Section icon={Banknote} title="Bank account"><Info label="Account holder" value={member.bank_account_holder_name ?? "Not provided"} /><Info label="Account number" value={maskAccount(member.bank_account_number)} /><Info label="Bank" value={member.bank_name ?? "Not provided"} /><Info label="Branch" value={member.bank_branch_name ?? "Not provided"} /><Info label="IFSC code" value={member.bank_ifsc_code ?? "Not provided"} /><Info label="Account type" value={member.bank_account_type ? title(member.bank_account_type) : "Not provided"} /></Section><Section icon={FileCheck2} title="Documents"><div className="space-y-2"><Document memberId={id} type="aadhaar" label="Aadhaar document" name={member.aadhaar_document_file_name} /><Document memberId={id} type="pan" label="PAN document" name={member.pan_document_file_name} /><Document memberId={id} type="cheque" label="Cancelled cheque" name={member.cheque_file_name} /><Document memberId={id} type="bank-statement" label="Bank statement" name={member.bank_statement_file_name} /></div></Section></div>
    </div>
  </div>;
}

async function fetchPrivateFile(id: string, type: string): Promise<string> { const token = localStorage.getItem("zchit_access_token"); const response = await fetch(`${API_URL}/api/v1/members/${id}/documents/${type}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(await getResponseError(response, "Unable to open document.")); return URL.createObjectURL(await response.blob()); }
function Section({ icon: Icon, title, children }: { icon: typeof UserRound; title: string; children: React.ReactNode }) { return <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="border-b border-slate-200 p-3.5"><div className="flex items-center gap-2"><Icon className="size-4 text-emerald-700" /><CardTitle className="text-xs font-bold text-slate-950">{title}</CardTitle></div></CardHeader><CardContent className="overflow-visible p-3.5">{children}</CardContent></Card>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between border-b border-slate-100 py-2 last:border-0"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="text-xs font-bold text-slate-950">{value}</p></div>; }
function Document({ memberId, type, label, name }: { memberId: string; type: string; label: string; name: string | null }) { async function open() { if (!name) return; const url = await fetchPrivateFile(memberId, type); window.open(url, "_blank", "noopener,noreferrer"); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } return <div className="flex items-center gap-3 rounded-lg border border-slate-200 p-3"><span className="flex size-8 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FileText className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-slate-900">{label}</p><p className="truncate text-[10px] text-slate-500">{name ?? "Not uploaded"}</p></div><Button type="button" variant="ghost" size="icon-sm" disabled={!name} onClick={open} aria-label={`Open ${label}`}><Download className="size-3.5" /></Button></div>; }
function FinancialCard({ icon: Icon, label, value, note, tone }: { icon: typeof Gavel; label: string; value: string; note: string; tone: "emerald" | "violet" }) { const styles = tone === "emerald" ? "bg-emerald-50 text-emerald-700" : "bg-violet-50 text-violet-700"; return <div className="flex items-center gap-3 rounded-lg border border-slate-200 bg-slate-50/60 p-3"><span className={`flex size-9 items-center justify-center rounded-lg ${styles}`}><Icon className="size-4" /></span><div className="min-w-0"><p className="text-[9px] font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-0.5 text-base font-bold text-slate-950">{value}</p><p className="truncate text-[9px] text-slate-500">{note}</p></div></div>; }
function formatDate(value: string | null) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-IN") : "Not provided"; }
function maskAccount(value: string | null) { return value ? `${"•".repeat(Math.max(0, value.length - 4))}${value.slice(-4)}` : "Not provided"; }
function title(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
function KycSheet({ onSubmit }: { onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { return <Sheet><SheetTrigger render={<Button variant="outline" className="h-8" />}>Review KYC</SheetTrigger><SheetContent><SheetHeader><SheetTitle>KYC verification review</SheetTitle></SheetHeader><form onSubmit={onSubmit} className="space-y-4 px-4"><div className="space-y-1.5"><Label>Aadhaar status</Label><select name="aadhaar_status" className="h-9 w-full rounded-md border border-slate-300 px-3" required><option value="verified">Verified</option><option value="rejected">Rejected</option></select></div><div className="space-y-1.5"><Label>PAN status</Label><select name="pan_status" className="h-9 w-full rounded-md border border-slate-300 px-3" required><option value="verified">Verified</option><option value="rejected">Rejected</option><option value="not_applicable">Not applicable</option></select></div><div className="space-y-1.5"><Label>Review notes</Label><Input name="notes" /></div><div className="space-y-1.5"><Label>Rejection reason</Label><Input name="rejection_reason" /></div><Button type="submit" className="w-full bg-emerald-600 text-white">Save KYC decision</Button></form></SheetContent></Sheet>; }
