"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, Crosshair, MapPin, Route } from "lucide-react";
import { AgentMap } from "@/components/agents/agent-map";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { authenticatedApiRequest } from "@/lib/api";

type Agent={id:number;employee_name:string;employee_code:string;shift_status:string;last_latitude:string|null;last_longitude:string|null;last_location_at:string|null};
type RouteData={shift?:{id:number;status:string;checked_in_at:string;checked_out_at:string|null}|null;points:{latitude:string;longitude:string;received_at:string}[]};

export default function AgentMapPage(){
  const params=useSearchParams();const requested=Number(params.get("agent"))||null;const[agents,setAgents]=useState<Agent[]>([]);const[routes,setRoutes]=useState<Record<number,RouteData>>({});const[selected,setSelected]=useState<number|null>(requested);const[error,setError]=useState("");
  async function load(){const items=await authenticatedApiRequest<Agent[]>("/api/v1/admin/collection-agents");const located=items.filter(item=>item.last_latitude&&item.last_longitude);const pairs=await Promise.all(located.map(item=>authenticatedApiRequest<RouteData>(`/api/v1/admin/collection-agents/${item.id}/locations`).then(route=>[item.id,route] as const)));setAgents(items);setRoutes(Object.fromEntries(pairs));setSelected(current=>current??located[0]?.id??null);}
  useEffect(()=>{const timer=setTimeout(()=>void load().catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load map.")),0);const interval=setInterval(()=>void load().catch(()=>undefined),15000);return()=>{clearTimeout(timer);clearInterval(interval);};},[]);
  const selectedAgent=agents.find(item=>item.id===selected);const selectedRoute=selected?routes[selected]:undefined;
  return <div className="mx-auto max-w-[1600px] space-y-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Button nativeButton={false} variant="outline" size="icon" render={<Link href="/dashboard/agents"/>}><ArrowLeft className="size-4"/></Button><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Field tracking</p><h1 className="text-2xl font-bold">Live agent map</h1><p className="text-[13px] text-slate-600">Check-in time, current location, and today&apos;s travelled route.</p></div></div><Badge className="bg-emerald-50 text-emerald-700">Refreshes every 15 seconds</Badge></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-3"><Stat icon={Crosshair} label="On duty" value={agents.filter(item=>item.shift_status==="active").length}/><Stat icon={MapPin} label="Located agents" value={agents.filter(item=>item.last_latitude&&item.last_longitude).length}/><Stat icon={Route} label="Today travel points" value={selectedRoute?.points.length??0}/></div><Card className="overflow-hidden border border-slate-200 bg-white py-0 ring-0"><CardHeader className="flex flex-row items-center justify-between border-b p-4"><div><CardTitle className="text-sm">Google Maps tracking</CardTitle><p className="mt-1 text-[10px] text-slate-500">Marker shows current location · line shows today&apos;s travel</p></div>{selectedAgent&&<Badge>{selectedAgent.employee_name}</Badge>}</CardHeader><CardContent className="p-3"><AgentMap agents={agents} selectedAgentId={selected} routes={routes} onSelect={setSelected}/></CardContent></Card>{selectedAgent&&<Card className="border border-slate-200 bg-white py-0 ring-0"><CardContent className="grid gap-4 p-4 sm:grid-cols-5"><Info label="Agent" value={`${selectedAgent.employee_name} · ${selectedAgent.employee_code}`}/><Info label="Check-in time" value={selectedRoute?.shift?.checked_in_at?new Date(selectedRoute.shift.checked_in_at).toLocaleString("en-IN"):"Not checked in"}/><Info label="Check-in time" value={selectedRoute?.shift?.checked_in_at?new Date(selectedRoute.shift.checked_in_at).toLocaleString("en-IN"):"Not checked in"}/><Info label="Check-out time" value={selectedRoute?.shift?.checked_out_at?new Date(selectedRoute.shift.checked_out_at).toLocaleString("en-IN"):"Shift active"}/><Info label="Current location" value={selectedAgent.last_latitude&&selectedAgent.last_longitude?`${selectedAgent.last_latitude}, ${selectedAgent.last_longitude}`:"No GPS"}/><Info label="Today travel time" value={routeDuration(selectedRoute)}/></CardContent></Card>}</div>;
}
function routeDuration(route?:RouteData){if(!route?.shift)return "No shift";const start=new Date(route.shift.checked_in_at).getTime();const end=route.shift.checked_out_at?new Date(route.shift.checked_out_at).getTime():Date.now();const minutes=Math.max(0,Math.round((end-start)/60000));return `${Math.floor(minutes/60)}h ${minutes%60}m`;}
function Stat({icon:Icon,label,value}:{icon:typeof Route;label:string;value:number}){return <Card className="border border-slate-200 bg-white py-0 ring-0"><CardContent className="flex items-center gap-3 p-4"><Icon className="size-5 text-emerald-700"/><div><p className="text-xs text-slate-600">{label}</p><p className="text-xl font-bold">{value}</p></div></CardContent></Card>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xs font-bold capitalize text-slate-950">{value}</p></div>}
