"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";
import { ArrowLeft, BadgeIndianRupee, CheckCircle2, Clock3, Gavel, Phone } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { authenticatedApiRequest } from "@/lib/api";

type Row = { schedule_id: number; installment_number: number; due_date: string; payable_amount: string; receivable_amount: string; status: string; paid_amount: string | null; payment_date: string | null; payment_mode: string | null; reference_number: string | null; auction_id: number | null; payout_amount: string | null; net_payout_amount: string | null };
type Ledger = { group_id: number; group_code: string; scheme_name: string; member_id: number; member_code: string; member_name: string; mobile_number: string; rows: Row[] };
export default function MemberLedgerPage({ params }: { params: Promise<{ id: string; memberId: string }> }) {
  const { id, memberId } = use(params); const [ledger, setLedger] = useState<Ledger | null>(null); const [error, setError] = useState("");
  useEffect(() => { const timer = setTimeout(async () => { try { setLedger(await authenticatedApiRequest<Ledger>(`/api/v1/chits/${id}/members/${memberId}/ledger`)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load ledger."); } }, 0); return () => clearTimeout(timer); }, [id, memberId]);
  if (error) return <p className="rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p>; if (!ledger) return <p className="p-8 text-center text-sm text-slate-500">Loading ledger…</p>;
  const paid = ledger.rows.filter(row => row.status === "paid").reduce((sum, row) => sum + Number(row.paid_amount), 0); const settled = ledger.rows.filter(row => row.status === "settled_against_payout").length;
  return <div className="mx-auto max-w-6xl space-y-4"><div className="flex items-center gap-3"><Button nativeButton={false} variant="outline" size="icon" render={<Link href={`/dashboard/chits/${id}`} />}><ArrowLeft className="size-4" /></Button><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-700">{ledger.group_code} · {ledger.member_code}</p><h1 className="mt-0.5 text-xl font-bold">{ledger.member_name}</h1><p className="mt-1 flex items-center gap-1.5 text-xs text-slate-500"><Phone className="size-3.5" />{ledger.mobile_number} · {ledger.scheme_name}</p></div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Summary icon={BadgeIndianRupee} label="Cash paid" value={`₹${paid.toLocaleString("en-IN")}`} /><Summary icon={CheckCircle2} label="Paid installments" value={String(ledger.rows.filter(row => row.status === "paid").length)} /><Summary icon={Gavel} label="Payout settlements" value={String(settled)} /></div>
    <Card className="border border-slate-200 bg-white py-0 ring-0"><CardHeader className="border-b p-4"><CardTitle className="text-sm">Full installment ledger</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[880px] text-xs"><thead className="bg-slate-50"><tr>{["#","Date","Payable","Receivable","Paid / settled","Payment details","Status"].map(value => <th key={value} className="p-3 text-left">{value}</th>)}</tr></thead><tbody>{ledger.rows.map(row => <tr key={row.schedule_id} className="border-t"><td className="p-3 font-bold">{row.installment_number}</td><td className="p-3">{new Date(row.due_date).toLocaleDateString("en-IN")}</td><td className="p-3 font-bold">₹{Number(row.payable_amount).toLocaleString("en-IN")}</td><td className="p-3 font-bold text-emerald-700">₹{Number(row.receivable_amount).toLocaleString("en-IN")}</td><td className="p-3">{row.status === "settled_against_payout" ? `₹${Number(row.payable_amount).toLocaleString("en-IN")} adjusted` : row.paid_amount ? `₹${Number(row.paid_amount).toLocaleString("en-IN")}` : "—"}</td><td className="p-3">{row.status === "settled_against_payout" ? <span className="text-emerald-700">Payout ₹{Number(row.payout_amount).toLocaleString("en-IN")} · Net ₹{Number(row.net_payout_amount).toLocaleString("en-IN")}</span> : row.payment_date ? `${row.payment_date} · ${row.payment_mode?.toUpperCase()}${row.reference_number ? ` · ${row.reference_number}` : ""}` : "—"}</td><td className="p-3"><Status value={row.status} /></td></tr>)}</tbody></table></CardContent></Card>
  </div>;
}
function Status({ value }: { value: string }) { const styles: Record<string,string> = { paid:"bg-emerald-50 text-emerald-700", pending:"bg-blue-50 text-blue-700", overdue:"bg-red-50 text-red-700", settled_against_payout:"bg-violet-50 text-violet-700" }; return <Badge className={styles[value]}>{value === "settled_against_payout" ? "Settled against payout" : value}</Badge>; }
function Summary({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <Card className="border border-slate-200 bg-white py-0 ring-0"><CardContent className="flex items-center gap-3 p-4"><Icon className="size-5 text-emerald-700" /><div><p className="text-[10px] text-slate-500">{label}</p><p className="text-sm font-bold">{value}</p></div></CardContent></Card>; }
