"use client";

import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
	import { Copy, KeyRound, Laptop, LockKeyhole, LogOut, RefreshCcw, ShieldCheck, Smartphone, Trash2, TriangleAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { authenticatedApiRequest, clearSession } from "@/lib/api";
import { CommunicationSettings } from "@/components/communication-settings";

type Security={email:string;role:string;mfa_enabled:boolean;mfa_enabled_at:string|null;recovery_codes_remaining:number;active_sessions:number;password_updated_at:string};
type Session={id:number;ip_address:string|null;user_agent:string|null;created_at:string;last_used_at:string|null;expires_at:string};
type Setup={secret:string;otpauth_uri:string;qr_code_data_url:string};
function device(value:string|null){if(!value)return "Unknown device";if(/mobile|android|iphone/i.test(value))return "Mobile device";if(/mac/i.test(value))return "Mac";if(/windows/i.test(value))return "Windows PC";return "Web browser";}
function dateTime(value:string|null){return value?new Date(value).toLocaleString("en-IN"):"Not available";}

export default function SettingsPage(){const[security,setSecurity]=useState<Security|null>(null);const[sessions,setSessions]=useState<Session[]>([]);const[setup,setSetup]=useState<Setup|null>(null);const[recoveryCodes,setRecoveryCodes]=useState<string[]>([]);const[error,setError]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
 async function load(){const[status,active]=await Promise.all([authenticatedApiRequest<Security>("/api/v1/auth/security"),authenticatedApiRequest<Session[]>("/api/v1/auth/sessions")]);setSecurity(status);setSessions(active);}
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load security settings.")).finally(()=>setLoading(false)),0);return()=>clearTimeout(timer);},[]);
 async function action(work:()=>Promise<unknown>,success:string){setError("");setMessage("");try{await work();setMessage(success);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Security action failed.");}}
 async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const next=String(data.get("new_password"));if(next!==String(data.get("confirm_password"))){setError("New passwords do not match.");return;}await action(()=>authenticatedApiRequest("/api/v1/auth/change-password",{method:"POST",body:JSON.stringify({current_password:data.get("current_password"),new_password:next})}),"Password changed. Redirecting to sign in…");clearSession();setTimeout(()=>window.location.replace("/login"),900);}
 async function beginMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setError("");try{setSetup(await authenticatedApiRequest<Setup>("/api/v1/auth/mfa/setup",{method:"POST",body:JSON.stringify({current_password:data.get("current_password")})}));}catch(reason){setError(reason instanceof Error?reason.message:"Unable to start 2FA setup.");}}
 async function confirmMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setError("");try{const result=await authenticatedApiRequest<{message:string;recovery_codes:string[]}>("/api/v1/auth/mfa/confirm",{method:"POST",body:JSON.stringify({code:data.get("code")})});setRecoveryCodes(result.recovery_codes);setSetup(null);await load();setMessage("Two-factor authentication is now enabled.");}catch(reason){setError(reason instanceof Error?reason.message:"Invalid authenticator code.");}}
 async function regenerate(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setError("");try{const result=await authenticatedApiRequest<{recovery_codes:string[]}>("/api/v1/auth/mfa/recovery-codes",{method:"POST",body:JSON.stringify({current_password:data.get("current_password")})});setRecoveryCodes(result.recovery_codes);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to regenerate recovery codes.");}}
 async function disable(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!confirm("Disable two-factor authentication and sign out every device?"))return;const data=new FormData(event.currentTarget);await action(()=>authenticatedApiRequest("/api/v1/auth/mfa/disable",{method:"POST",body:JSON.stringify({current_password:data.get("current_password"),code:data.get("code")})}),"Two-factor authentication disabled.");clearSession();window.location.replace("/login");}
 async function revoke(id:number){await action(()=>authenticatedApiRequest(`/api/v1/auth/sessions/${id}`,{method:"DELETE"}),"Session revoked.");}
 async function revokeAll(){if(!confirm("Sign out every active device, including this browser?"))return;await action(()=>authenticatedApiRequest("/api/v1/auth/sessions/revoke-all",{method:"POST"}),"All sessions revoked.");clearSession();window.location.replace("/login");}
 if(loading)return <p className="p-10 text-center text-sm text-slate-600">Loading security settings…</p>;
 return <div className="mx-auto max-w-[1200px] space-y-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Account protection</p><h1 className="mt-1.5 text-2xl font-bold text-slate-950">Security settings</h1><p className="mt-1 text-[13px] text-slate-600">Manage your password, authenticator, recovery access, and signed-in devices.</p></div>{error&&<Notice tone="error" text={error}/>} {message&&<Notice tone="success" text={message}/>}<div className="grid gap-3 sm:grid-cols-3"><Summary icon={ShieldCheck} label="Two-factor authentication" value={security?.mfa_enabled?"Enabled":"Not enabled"} secure={Boolean(security?.mfa_enabled)}/><Summary icon={Laptop} label="Active sessions" value={String(security?.active_sessions??0)} secure/><Summary icon={KeyRound} label="Recovery codes" value={security?.mfa_enabled?`${security.recovery_codes_remaining} remaining`:"Unavailable"} secure={Boolean(security?.mfa_enabled&&security.recovery_codes_remaining)}/></div>
 <div className="grid gap-4 lg:grid-cols-2"><Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="border-b p-4"><CardTitle className="flex items-center gap-2 text-sm text-slate-950"><LockKeyhole className="size-4 text-emerald-700"/>Change password</CardTitle><p className="text-[11px] text-slate-600">Changing your password signs out every device.</p></CardHeader><CardContent className="p-4"><form onSubmit={changePassword} className="space-y-3"><Field label="Current password" name="current_password"/><Field label="New password" name="new_password"/><Field label="Confirm new password" name="confirm_password"/><Button type="submit" className="h-9 bg-emerald-600 text-white hover:bg-emerald-700">Update password</Button></form></CardContent></Card>
 <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="border-b p-4"><div className="flex items-center justify-between"><div><CardTitle className="flex items-center gap-2 text-sm text-slate-950"><Smartphone className="size-4 text-emerald-700"/>Authenticator 2FA</CardTitle><p className="mt-1 text-[11px] text-slate-600">Require a code after every successful password check.</p></div><Badge className={security?.mfa_enabled?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}>{security?.mfa_enabled?"Enabled":"Recommended"}</Badge></div></CardHeader><CardContent className="overflow-visible p-4">{!security?.mfa_enabled&&!setup?<form onSubmit={beginMfa} className="space-y-3"><Field label="Confirm current password" name="current_password"/><Button type="submit" className="h-9 bg-emerald-600 text-white hover:bg-emerald-700">Set up authenticator</Button></form>:setup?<div className="space-y-4"><p className="text-xs text-slate-700">Scan this QR code in Microsoft Authenticator, Google Authenticator, 1Password, or another TOTP app.</p><div className="flex flex-col gap-4 sm:flex-row"><Image src={setup.qr_code_data_url} alt="Authenticator QR code" width={180} height={180} unoptimized className="rounded-lg border"/><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase text-slate-700">Manual setup key</p><code className="mt-2 block break-all rounded-lg bg-slate-100 p-3 text-xs text-slate-900">{setup.secret}</code><form onSubmit={confirmMfa} className="mt-3 space-y-2"><Label className="text-xs text-slate-700">6-digit code</Label><Input name="code" required pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" className="h-9 font-mono tracking-widest"/><div className="flex gap-2"><Button type="submit" className="h-9 bg-emerald-600 text-white">Verify and enable</Button><Button type="button" variant="outline" className="h-9" onClick={()=>setSetup(null)}>Cancel</Button></div></form></div></div></div>:<div className="space-y-4"><p className="text-xs text-slate-700">Enabled {dateTime(security?.mfa_enabled_at ?? null)}. Keep recovery codes offline.</p><form onSubmit={regenerate} className="space-y-2"><Field label="Password to generate new recovery codes" name="current_password"/><Button type="submit" variant="outline" className="h-9"><RefreshCcw className="size-4"/>Regenerate recovery codes</Button></form><form onSubmit={disable} className="space-y-2 border-t pt-4"><Field label="Current password" name="current_password"/><div className="space-y-1.5"><Label className="text-xs text-slate-700">Authenticator code</Label><Input name="code" required maxLength={6} className="h-9 font-mono"/></div><Button type="submit" variant="outline" className="h-9 border-red-200 text-red-700 hover:bg-red-50"><Trash2 className="size-4"/>Disable 2FA</Button></form></div>}</CardContent></Card></div>
 {recoveryCodes.length>0&&<Card className="border-2 border-amber-300 bg-amber-50 py-0 ring-0"><CardContent className="p-5"><div className="flex items-start gap-3"><TriangleAlert className="mt-0.5 size-5 text-amber-700"/><div className="flex-1"><h2 className="font-bold text-slate-950">Save these recovery codes now</h2><p className="mt-1 text-xs text-slate-700">Each code works once. They will not be shown again.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{recoveryCodes.map(code=><code key={code} className="rounded-md border border-amber-200 bg-white px-3 py-2 text-center text-xs font-bold text-slate-900">{code}</code>)}</div><Button type="button" variant="outline" className="mt-4 h-9 bg-white" onClick={()=>void navigator.clipboard.writeText(recoveryCodes.join("\n"))}><Copy className="size-4"/>Copy all codes</Button></div></div></CardContent></Card>}
 <CommunicationSettings /> <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="flex flex-row items-center justify-between border-b p-4"><div><CardTitle className="text-sm text-slate-950">Active sessions</CardTitle><p className="mt-1 text-[11px] text-slate-600">Review browsers and devices with active refresh access.</p></div><Button type="button" variant="outline" className="h-9 border-red-200 text-red-700" onClick={()=>void revokeAll()}><LogOut className="size-4"/>Revoke all</Button></CardHeader><CardContent className="p-0">{sessions.length===0?<p className="p-6 text-center text-xs text-slate-600">No active sessions.</p>:sessions.map(item=><div key={item.id} className="flex items-center gap-3 border-b border-slate-100 p-4 last:border-0"><span className="flex size-10 items-center justify-center rounded-lg bg-slate-100"><Laptop className="size-4 text-slate-700"/></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-950">{device(item.user_agent)}</p><p className="mt-1 truncate text-[10px] text-slate-600">{item.ip_address??"Unknown IP"} · Signed in {dateTime(item.created_at)}</p><p className="mt-0.5 text-[10px] text-slate-500">Expires {dateTime(item.expires_at)}</p></div><Button type="button" variant="outline" size="sm" className="h-8 text-red-700" onClick={()=>void revoke(item.id)}>Revoke</Button></div>)}</CardContent></Card>
 </div>}
function Field({label,name}:{label:string;name:string}){return <div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">{label}</Label><Input name={name} type="password" required minLength={8} autoComplete={name==="current_password"?"current-password":"new-password"} className="h-9"/></div>}
function Notice({tone,text}:{tone:"error"|"success";text:string}){return <p className={`rounded-lg border p-3 text-xs ${tone==="error"?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{text}</p>}
function Summary({icon:Icon,label,value,secure}:{icon:typeof ShieldCheck;label:string;value:string;secure:boolean}){return <Card className="border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardContent className="flex items-center gap-3 p-4"><span className={`flex size-9 items-center justify-center rounded-lg ${secure?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}><Icon className="size-4"/></span><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-700">{label}</p><p className="mt-1 text-sm font-bold text-slate-950">{value}</p></div></CardContent></Card>}
