"use client";

import Link from "next/link";
import { FormEvent, use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Banknote, MapPin, Plus, Trash2, UserRound, UsersRound } from "lucide-react";
import { FormMessage } from "@/components/auth/form-message";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ApiRequestError, authenticatedApiRequest } from "@/lib/api";

type Reference = { id: number; name: string; mobile_number: string; relationship: string | null };
type Member = { id: number; full_name: string; date_of_birth: string | null; mobile_number: string; email: string | null; aadhaar_last4: string; pan: string | null; nominee_name: string | null; nominee_relationship: string | null; nominee_mobile_number: string | null; nominee_date_of_birth: string | null; bank_account_holder_name: string | null; bank_account_number: string | null; bank_name: string | null; bank_branch_name: string | null; bank_ifsc_code: string | null; bank_account_type: string | null; address_line_1: string; address_line_2: string | null; locality: string | null; city: string; state: string; postal_code: string; country: string; landmark: string | null; references: Reference[] };
const fieldClass = "h-9 border-slate-300 bg-white text-sm text-slate-950";

export default function EditMemberPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const router = useRouter(); const [member, setMember] = useState<Member | null>(null); const [references, setReferences] = useState<Reference[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(async () => { try { const data = await authenticatedApiRequest<Member>(`/api/v1/members/${id}`); setMember(data); setReferences(data.references); } catch (err) { if (err instanceof ApiRequestError && err.status === 401) window.location.replace("/login"); else setError(err instanceof Error ? err.message : "Unable to load member."); } }, 0); return () => window.clearTimeout(timer); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!member) return; setLoading(true); setError(""); const data = new FormData(event.currentTarget); const optional = (name: string) => String(data.get(name) ?? "").trim() || null; try { await authenticatedApiRequest(`/api/v1/members/${id}`, { method: "PUT", body: JSON.stringify({ full_name: data.get("full_name"), date_of_birth: optional("date_of_birth"), mobile_number: data.get("mobile_number"), email: optional("email"), aadhaar_number: optional("aadhaar_number"), pan: optional("pan"), nominee_name: optional("nominee_name"), nominee_relationship: optional("nominee_relationship"), nominee_mobile_number: optional("nominee_mobile_number"), nominee_date_of_birth: optional("nominee_date_of_birth"), bank_account_holder_name: optional("bank_account_holder_name"), bank_account_number: optional("bank_account_number"), bank_name: optional("bank_name"), bank_branch_name: optional("bank_branch_name"), bank_ifsc_code: optional("bank_ifsc_code"), bank_account_type: optional("bank_account_type")?.toLowerCase(), address_line_1: data.get("address_line_1"), address_line_2: optional("address_line_2"), locality: optional("locality"), city: data.get("city"), state: data.get("state"), postal_code: data.get("postal_code"), country: "India", landmark: optional("landmark"), references: references.map((_, index) => ({ name: data.get(`reference_name_${index}`), mobile_number: data.get(`reference_number_${index}`), relationship: optional(`reference_relationship_${index}`) })) }) }); router.push(`/dashboard/members/${id}`); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update member."); } finally { setLoading(false); } }
  if (!member && !error) return <p className="p-8 text-center text-sm text-slate-500">Loading member…</p>;
  return <div className="mx-auto max-w-3xl space-y-3"><div className="flex items-center gap-3"><Button nativeButton={false} variant="outline" size="icon" render={<Link href={`/dashboard/members/${id}`} />}><ArrowLeft className="size-4" /></Button><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-700">Member management</p><h1 className="mt-0.5 text-lg font-bold text-slate-950">Edit member</h1></div></div>{error && <FormMessage type="error">{error}</FormMessage>}{member && <form onSubmit={submit} className="space-y-3">
    <Section icon={UserRound} title="Personal & KYC information"><div className="grid gap-3 sm:grid-cols-2"><Field label="Full name" name="full_name" required defaultValue={member.full_name} /><Field label="Date of birth" name="date_of_birth" type="date" defaultValue={member.date_of_birth ?? ""} /><Field label="Mobile number" name="mobile_number" required defaultValue={member.mobile_number} /><Field label="Email" name="email" type="email" defaultValue={member.email ?? ""} /><Field label="PAN" name="pan" maxLength={10} defaultValue={member.pan ?? ""} /><div className="sm:col-span-2"><Field label={`New Aadhaar number (currently •••• ${member.aadhaar_last4})`} name="aadhaar_number" placeholder="Leave blank to keep current Aadhaar" maxLength={14} /></div></div></Section>
    <Section icon={UsersRound} title="Nominee details"><div className="grid gap-3 sm:grid-cols-2"><Field label="Nominee name" name="nominee_name" defaultValue={member.nominee_name ?? ""} /><Field label="Relationship" name="nominee_relationship" defaultValue={member.nominee_relationship ?? ""} /><Field label="Mobile number" name="nominee_mobile_number" defaultValue={member.nominee_mobile_number ?? ""} /><Field label="Date of birth" name="nominee_date_of_birth" type="date" defaultValue={member.nominee_date_of_birth ?? ""} /></div></Section>
    <Section icon={MapPin} title="Residential address"><div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Address line 1" name="address_line_1" required defaultValue={member.address_line_1} /></div><div className="sm:col-span-2"><Field label="Address line 2" name="address_line_2" defaultValue={member.address_line_2 ?? ""} /></div><Field label="Locality" name="locality" defaultValue={member.locality ?? ""} /><Field label="Landmark" name="landmark" defaultValue={member.landmark ?? ""} /><Field label="City" name="city" required defaultValue={member.city} /><Field label="State" name="state" required defaultValue={member.state} /><Field label="Postal code" name="postal_code" required defaultValue={member.postal_code} /><div className="space-y-1.5"><Label className="text-xs font-semibold text-slate-700">Country</Label><Input value="India" readOnly className={`${fieldClass} bg-slate-50`} /></div></div></Section>
    <Section icon={UserRound} title="References"><div className="space-y-2">{references.map((reference, index) => <div key={reference.id} className="grid gap-2 rounded-lg border border-slate-200 bg-slate-50 p-3 sm:grid-cols-[1fr_1fr_.8fr_auto]"><Field label="Reference name" name={`reference_name_${index}`} required defaultValue={reference.name} /><Field label="Mobile number" name={`reference_number_${index}`} required defaultValue={reference.mobile_number} /><Field label="Relationship" name={`reference_relationship_${index}`} defaultValue={reference.relationship ?? ""} /><Button type="button" variant="ghost" size="icon" className="self-end text-red-700" onClick={() => setReferences(current => current.filter(item => item.id !== reference.id))}><Trash2 className="size-4" /></Button></div>)}<Button type="button" variant="outline" className="h-8 text-xs" onClick={() => setReferences(current => [...current, { id: Date.now(), name: "", mobile_number: "", relationship: null }])}><Plus className="size-3.5" />Add reference</Button></div></Section>
    <Section icon={Banknote} title="Bank account details"><div className="grid gap-3 sm:grid-cols-2"><Field label="Account holder name" name="bank_account_holder_name" defaultValue={member.bank_account_holder_name ?? ""} /><Field label="Account number" name="bank_account_number" defaultValue={member.bank_account_number ?? ""} /><Field label="Bank name" name="bank_name" defaultValue={member.bank_name ?? ""} /><Field label="Branch name" name="bank_branch_name" defaultValue={member.bank_branch_name ?? ""} /><Field label="IFSC code" name="bank_ifsc_code" maxLength={11} defaultValue={member.bank_ifsc_code ?? ""} /><Field label="Account type" name="bank_account_type" placeholder="savings / current / other" defaultValue={member.bank_account_type ?? ""} /></div></Section>
    <div className="flex justify-end"><Button type="submit" disabled={loading} className="h-9 bg-emerald-600 px-5 font-semibold text-white hover:bg-emerald-700">{loading ? "Saving…" : <>Save changes <ArrowRight className="size-4" /></>}</Button></div>
  </form>}</div>;
}
function Section({ icon: Icon, title, children }: { icon: typeof UserRound; title: string; children: React.ReactNode }) { return <Card className="overflow-visible border border-slate-200 bg-white py-0 shadow-sm ring-0"><CardHeader className="border-b border-slate-200 px-3.5 py-3"><div className="flex items-center gap-2"><Icon className="size-3.5 text-emerald-700" /><CardTitle className="text-xs font-bold text-slate-950">{title}</CardTitle></div></CardHeader><CardContent className="overflow-visible p-3.5">{children}</CardContent></Card>; }
function Field({ label, name, required, type = "text", placeholder, maxLength, defaultValue }: { label: string; name: string; required?: boolean; type?: string; placeholder?: string; maxLength?: number; defaultValue?: string }) { return <div className="space-y-1.5"><Label htmlFor={name} className="text-xs font-semibold text-slate-700">{label}{required && <span className="text-red-600"> *</span>}</Label><Input id={name} name={name} type={type} required={required} placeholder={placeholder} maxLength={maxLength} defaultValue={defaultValue} className={fieldClass} /></div>; }
